#!/usr/bin/env python3
"""
Deterministic generator for data/minigrid.json (stdlib only).

Grid math: a 5x5 grid where every entry must be length >= 3 and every open
cell must be "checked" (belongs to both an across and a down entry) can only
place blocks in its four corners. Proof: for a row of width 5, a single block
at column c splits it into runs of length c and 4-c; both must be 0 or >= 3,
which is only true for c=0 or c=4. Two blocks in one row only work at columns
0 and 4 together (leaving a middle run of exactly 3). The same holds for
columns. A block therefore has to satisfy both its row's rule and its
column's rule at once, which is only possible at (0,0), (0,4), (4,0), (4,4).
So there are exactly three symmetric block counts: 0, 2 (one diagonal pair),
or 4 (all corners). TEMPLATES below is the complete list, not a subset.

Fill strategy: rather than pull answers from the full wordlist (which would
mean auto-generated, unclued fill), every answer this generator can place
comes from CLUES, a hand-written word -> clue dictionary. That keeps the
"every clue must match its answer" rule trivially true and puts the quality
budget where the contract asks for it: the clues themselves. No word may
appear twice in one puzzle (once across, once down); see enumerate_solutions.

Search strategy: enumerate_solutions runs one exhaustive depth-first search
per block template and collects every complete filling it finds, instead of
the more obvious "random restart until something works" approach. With a
curated (not encyclopedic) word list, valid fillings for a fully-crossed
template are a small, oddly shaped island in the search space; independent
restarts kept rediscovering the same handful and burning their budget on the
rest, while a single search that keeps going past the first hit explores
that island completely and finds every solution in it. transpose_puzzle then
doubles the yield for free: swapping rows and columns turns every across
entry into a down entry reading the same letters in the same order, so it's
always a second valid, distinct puzzle from the same fill.
"""

import argparse
import json
import random
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT / "data" / "minigrid.json"
WORDLIST_PATH = ROOT / "data" / "wordlist.txt"
SIZE = 5

# ---------------------------------------------------------------------------
# Curated fill: every word below is common, plain, and family-friendly, with
# a one-line clue written for this puzzle (not scraped, not templated).
# ---------------------------------------------------------------------------

WORDS_3 = {
    "ACE": "Tennis serve the returner never touches",
    "AGE": "Number that climbs every birthday",
    "AID": "Help, in a pinch",
    "AIM": "Point a dart, say",
    "AIR": "What a slow leak lets out of a tire",
    "ANT": "Picnic crasher",
    "APE": "Gorilla or chimp, loosely",
    "ARC": "Rainbow's shape",
    "ARM": "Sleeve's contents",
    "ART": "Museum wall filler",
    "ASH": "What's left after the fire",
    "ATE": "Finished dinner",
    "BAD": "Opposite of good",
    "BAG": "Grocery carrier",
    "BAN": "Official no",
    "BAR": "Where a bartender works",
    "BAT": "Baseball swinger",
    "BAY": "Spot to anchor a ship",
    "BED": "Where you wake up",
    "BEE": "Honey maker",
    "BET": "Wager",
    "BIG": "Opposite of small",
    "BIN": "Recycling container",
    "BIT": "Small piece",
    "BOW": "Archer's weapon",
    "BOX": "Cardboard container",
    "BOY": "Young male",
    "BUD": "Flower before it blooms",
    "BUG": "Six-legged critter, or a coding error",
    "BUS": "School ride",
    "BUY": "Purchase",
    "CAB": "Taxi",
    "CAP": "Baseball hat",
    "CAR": "Vehicle with four wheels",
    "CAT": "Purring pet",
    "COB": "Corn's core",
    "COW": "Source of milk",
    "CRY": "Shed tears",
    "CUB": "Baby bear",
    "CUP": "Coffee holder",
    "CUT": "Scissors' job",
    "DAY": "24 hours",
    "DEN": "Cozy TV room",
    "DIG": "Shovel's job",
    "DIM": "Not bright",
    "DOG": "Best friend, canine",
    "DOT": "Point on an i",
    "DRY": "Not wet",
    "EAR": "Where earrings go",
    "EAT": "Have a meal",
    "EGG": "Omelet ingredient",
    "ELF": "Santa's helper",
    "END": "Story's last part",
    "ERA": "Historical span",
    "EYE": "Wink with it",
    "FAN": "Cooling device, or a devoted follower",
    "FAR": "Not near",
    "FAT": "Opposite of lean",
    "FEW": "Not many",
    "FIT": "In shape",
    "FIX": "Repair",
    "FLY": "Buzzing pest, or what a bird does",
    "FOG": "Low cloud on the road",
    "FOX": "Sly forest animal",
    "FUN": "Opposite of boring",
    "FUR": "Cat's coat",
    "GAP": "Space between",
    "GAS": "Fuel at the pump",
    "GEM": "Precious stone",
    "GUM": "Chewed, not swallowed",
    "GUN": "Firearm",
    "GUT": "Stomach, casually",
    "GYM": "Where you lift weights",
    "HAM": "Deli meat, or an overactor",
    "HAT": "Head covering",
    "HAY": "Barn bedding",
    "HEN": "Egg layer",
    "HIP": "Trendy, or a joint",
    "HOT": "Opposite of cold",
    "HUB": "Central point",
    "HUG": "Warm embrace",
    "ICE": "Frozen water",
    "ILL": "Under the weather",
    "INK": "Pen's fluid",
    "IVY": "Climbing plant, or a college league",
    "JAM": "Toast topper, or a traffic snarl",
    "JAR": "Pickle container",
    "JAW": "Chin's neighbor",
    "JOB": "Nine-to-five",
    "JOG": "Slow run",
    "JOY": "Pure happiness",
    "KEY": "Piano part, or a door opener",
    "KID": "Youngster",
    "LAP": "One trip around the track",
    "LAW": "Rule of the land",
    "LEG": "Table support, or a body part",
    "LID": "Jar's cap",
    "LIE": "Untruth",
    "LIP": "Mouth's edge",
    "LOG": "Fireplace fuel",
    "LOT": "Parking area",
    "LOW": "Not high",
    "MAD": "Furious",
    "MAN": "Adult male",
    "MAP": "Road trip guide",
    "MAT": "Wipe your feet here",
    "MAY": "Might, or the month before June",
    "MOB": "Unruly crowd",
    "MOM": "Mother",
    "MOP": "Floor cleaner",
    "MUD": "Rain's aftermath in the yard",
    "MUG": "Coffee cup with a handle",
    "NAP": "Short sleep",
    "NET": "Basketball hoop's fabric",
    "NEW": "Just released",
    "NOD": "Silent yes",
    "NOT": "Negation word",
    "NOW": "This very moment",
    "NUT": "Squirrel's snack",
    "OAK": "Sturdy tree, source of acorns",
    "OAR": "Rowboat's paddle",
    "ODD": "Not even",
    "OIL": "Car's lubricant",
    "OLD": "Not young",
    "ONE": "Loneliest number, per the song",
    "ORE": "Raw metal from a mine",
    "OWL": "Night bird, wise in stories",
    "OWN": "Possess",
    "PAD": "Sticky note stack",
    "PAL": "Buddy",
    "PAN": "Frying vessel",
    "PAW": "Dog's foot",
    "PAY": "Settle the bill",
    "PEA": "Tiny green vegetable",
    "PEN": "Ink writer",
    "PET": "Household animal",
    "PIE": "Thanksgiving dessert",
    "PIG": "Farm animal that oinks",
    "PIN": "Bowling target",
    "PIT": "Peach's center",
    "POD": "Peas' home",
    "POT": "Where soup simmers",
    "PUB": "British bar",
    "PUP": "Baby dog",
    "RAG": "Old cloth for cleaning",
    "RAN": "Past tense of run",
    "RAT": "Sewer rodent",
    "RAW": "Not cooked",
    "RAY": "Sunbeam",
    "RED": "Fire truck's color",
    "RIB": "Barbecue cut",
    "RID": "Get rid of",
    "RIM": "Basketball hoop's edge",
    "RIP": "Tear",
    "ROB": "Steal from",
    "ROT": "Decay",
    "ROW": "Line of seats",
    "RUB": "Massage motion",
    "RUG": "Living room floor cover",
    "RUN": "Jog faster",
    "SAD": "Feeling blue",
    "SAT": "Took a seat",
    "SAW": "Carpenter's cutting tool",
    "SEA": "Where ships sail",
    "SET": "Tennis chunk, or to place",
    "SIN": "Moral wrong",
    "SIP": "Small drink",
    "SIT": "Take a seat",
    "SIX": "Half a dozen",
    "SKY": "Above the clouds",
    "SLY": "Cunning",
    "SON": "Male child",
    "SOW": "Plant seeds",
    "SPA": "Massage retreat",
    "SPY": "Secret agent",
    "SUM": "Total",
    "SUN": "Daytime star",
    "TAG": "Playground chase game",
    "TAN": "Beach souvenir, skin-deep",
    "TAP": "Faucet",
    "TAX": "April's due bill",
    "TEA": "British afternoon drink",
    "TEN": "Perfect score, in gymnastics",
    "TIE": "Necktie, or a deadlocked score",
    "TIN": "Metal can material",
    "TIP": "Waiter's reward",
    "TOE": "Foot's tip",
    "TON": "2,000 pounds",
    "TOP": "Spinning toy",
    "TOW": "Pull a stalled car",
    "TOY": "Plaything",
    "TRY": "Give it a shot",
    "TUB": "Bath vessel",
    "TWO": "One plus one",
    "USE": "Put to work",
    "VAN": "Cargo vehicle",
    "VAT": "Big brewing tank",
    "WAR": "Opposite of peace",
    "WAX": "Candle material",
    "WAY": "Route",
    "WEB": "Spider's trap",
    "WET": "Not dry",
    "WIG": "Fake hair",
    "WIN": "Take first place",
    "WIT": "Quick humor",
    "YES": "Affirmative",
    "YET": "Not now, but soon",
    "ZOO": "Where the animals are kept",
}

# A second pass of common 3-letter fill. The corner entries in this game's
# grid shape are always length 3, so a bigger, more varied pool here does
# more for how many distinct clean puzzles the generator can find than
# almost any other lever (see the module docstring).
WORDS_3.update({
    "ADO": "Fuss, without much",
    "AFT": "Toward a ship's stern",
    "AGO": "In the past",
    "AHA": "Eureka moment's sound",
    "AIL": "Feel under the weather",
    "ALL": "Every last one",
    "AND": "Plus",
    "ANY": "Whichever one",
    "APT": "Fitting",
    "ARE": "Present tense of be",
    "ASK": "Request",
    "AXE": "Lumberjack's tool",
    "BEG": "Plead",
    "BIB": "Baby's mealtime cover",
    "BID": "Auction's offer",
    "BOA": "Feathery scarf, or a snake",
    "BOB": "Short haircut",
    "BOG": "Soggy marsh",
    "BOO": "Halloween's greeting",
    "BOP": "Light tap on the head",
    "BRA": "Undergarment",
    "BUM": "Lazy loafer",
    "BUN": "Burger's bread",
    "BYE": "Casual farewell",
    "CAM": "Engine's rotating part",
    "CAN": "Soup's metal container",
    "COD": "Fish and chips' fish",
    "COG": "Gear's tooth",
    "CON": "Scam, or against",
    "COO": "Pigeon's sound",
    "COP": "Police officer",
    "COT": "Camping's fold-up bed",
    "COY": "Playfully shy",
    "CUD": "Cow's re-chewed meal",
    "CUE": "Actor's prompt",
    "CUR": "Mangy mutt",
    "DAB": "Small amount, or a dance move",
    "DAD": "Father",
    "DAM": "Beaver's construction",
    "DEW": "Morning grass's moisture",
    "DID": "Past tense of do",
    "DIE": "Board game's cube",
    "DIP": "Chips' companion",
    "DOE": "Female deer",
    "DON": "Put on, or a mob boss",
    "DUB": "Give a new name to",
    "DUD": "Fizzled firework",
    "DUE": "Owed, or expected",
    "DUG": "Past tense of dig",
    "DUO": "Pair",
    "DYE": "Change a fabric's color",
    "EBB": "Tide's outward pull",
    "ELK": "Big antlered deer",
    "ELM": "Shady street tree",
    "EON": "Really long stretch of time",
    "EVE": "Night before",
    "EWE": "Female sheep",
    "FAD": "Short-lived trend",
    "FAX": "Old office machine's send",
    "FED": "Gave dinner to",
    "FEE": "Charge",
    "FIB": "Small lie",
    "FIG": "Sweet Mediterranean fruit",
    "FIN": "Shark's steering part",
    "FLU": "Winter's common bug",
    "FOE": "Enemy",
    "FOR": "In favor of",
    "FRO": "To and ___",
    "FRY": "Cook in hot oil",
    "GAB": "Chat idly",
    "GAG": "Comedy bit",
    "GAL": "Girl, casually",
    "GEL": "Hair styling goop",
    "GET": "Obtain",
    "GNU": "African antelope",
    "GUY": "Fellow",
    "HAG": "Storybook witch",
    "HEM": "Skirt's folded edge",
    "HER": "Not him",
    "HEW": "Chop with an axe",
    "HEY": "Casual greeting",
    "HID": "Past tense of hide",
    "HIM": "Not her",
    "HIS": "Belonging to him",
    "HIT": "Chart-topping song",
    "HOB": "Stovetop, in British English",
    "HOG": "Greedy eater, or a pig",
    "HOP": "Bunny's move",
    "HOW": "In what way",
    "HUE": "Shade of color",
    "HUM": "Wordless tune",
    "HUT": "Simple shelter",
    "ICY": "Slippery with frost",
    "INN": "Cozy roadside lodging",
    "ION": "Charged particle",
    "IRE": "Anger",
    "ITS": "Belonging to it",
    "JAB": "Boxing's quick punch",
    "JAY": "Blue backyard bird",
    "JET": "Fast plane",
    "JIG": "Lively folk dance",
    "JOT": "Write down quickly",
    "JUG": "Milk's big container",
    "JUT": "Stick out",
    "KEG": "Party's beer barrel",
    "KIN": "Relatives",
    "KIT": "Model plane's box of parts",
    "LAB": "Science class's workroom",
    "LAD": "Young boy",
    "LAG": "Video call's delay",
    "LAY": "Set down",
    "LET": "Allow",
    "LIT": "Turned on, or well-read",
    "LOB": "Tennis's soft high shot",
    "LYE": "Harsh soap-making chemical",
    "MEN": "Plural of man",
    "MET": "Past tense of meet",
    "MID": "Halfway through",
    "MIX": "Blend together",
    "MOD": "Stylish 1960s look",
    "MOO": "Cow's sound",
    "MOW": "Cut the grass",
    "MUM": "Silent, or British mother",
    "NAB": "Catch in the act",
    "NIL": "Zero, in soccer scores",
    "NIP": "Small bite, or chilly air",
    "NOR": "Neither this ___ that",
    "NUB": "Small remaining stub",
    "NUN": "Convent's resident",
    "OAT": "Porridge's grain",
    "OFF": "Not on",
    "OPT": "Choose",
    "ORB": "Glowing sphere",
    "OUR": "Belonging to us",
    "OUT": "Not in",
    "OWE": "Have a debt",
    "PAT": "Gentle tap on the back",
    "PEG": "Clothesline's clip",
    "PEP": "Enthusiastic energy",
    "POP": "Soda, in some regions",
    "PRY": "Snoop",
    "PUG": "Flat-faced little dog",
    "PUN": "Wordplay joke",
    "PUT": "Place",
    "RAM": "Butt with force, or a male sheep",
    "RAP": "Rhythmic spoken music",
    "REV": "Gun the engine",
    "RIG": "Big truck",
    "ROD": "Fishing pole",
    "RUM": "Pirate's spirit",
    "RUT": "Stuck routine",
    "RYE": "Deli bread",
    "SAG": "Droop",
    "SAP": "Tree's sticky fluid",
    "SAY": "Speak",
    "SEW": "Stitch",
    "SHY": "Bashful",
    "SIR": "Formal address for a man",
    "SKI": "Slope's gliding gear",
    "SOB": "Cry hard",
    "SOD": "Roll-out lawn turf",
    "SOY": "Tofu's source bean",
    "SUB": "Submarine, for short",
    "TAB": "Restaurant's running total",
    "TAR": "Road's paving material",
    "THE": "Most common word in English",
    "TUG": "Firm pull",
    "URN": "Coffee's big dispenser",
    "VET": "Animal doctor",
    "VIA": "By way of",
    "VOW": "Wedding's promise",
    "WAG": "Dog's tail move",
    "WAS": "Past tense of is",
    "WED": "Marry",
    "WHO": "Which person",
    "WHY": "For what reason",
    "WOE": "Deep sorrow",
    "WOK": "Stir-fry pan",
    "WON": "Past tense of win",
    "WOO": "Court romantically",
    "WOW": "Expression of amazement",
    "YAM": "Sweet potato's cousin",
    "YAP": "Small dog's bark",
    "YOU": "The person reading this",
    "ZAP": "Zap with a laser",
    "ZEN": "Meditative calm",
    "ZIP": "Fasten a jacket, or zero",
})

WORDS_4 = {
    "ABLE": "Capable",
    "ACID": "Vinegar's chemical class",
    "ACRE": "Farmland unit",
    "ACTS": "Play's divisions",
    "AFAR": "From a distance",
    "ALSO": "In addition",
    "AMID": "In the middle of",
    "ARCH": "Curved doorway shape",
    "AREA": "Square footage",
    "ARMY": "Ground force",
    "ATOM": "Smallest unit of an element",
    "AUNT": "Mom's sister",
    "AWAY": "Not here",
    "BABY": "Infant",
    "BACK": "Spine's location",
    "BAKE": "Oven activity",
    "BALD": "Hairless",
    "BALL": "Round toy",
    "BAND": "Rock group",
    "BANK": "Where you deposit checks",
    "BARE": "Not covered",
    "BARK": "Dog's sound, or a tree's covering",
    "BARN": "Farm building",
    "BASE": "Home plate's kin",
    "BATH": "Tub soak",
    "BEAM": "Sunlight ray, or a wooden support",
    "BEAN": "Coffee's raw form",
    "BEAR": "Grizzly, for one",
    "BEAT": "Drum's rhythm",
    "BEEF": "Burger's meat",
    "BEEN": "Past participle of be",
    "BELL": "Church tower sound",
    "BELT": "Waist accessory",
    "BEND": "Curve in the road",
    "BEST": "Top choice",
    "BIRD": "Robin or wren",
    "BITE": "Sandwich taste",
    "BLUE": "Sky's color",
    "BOAT": "Lake vessel",
    "BODY": "Torso and limbs",
    "BOIL": "Water at 212 degrees",
    "BOLD": "Not shy",
    "BOND": "007's title, or a financial IOU",
    "BONE": "Skeleton piece",
    "BOOK": "Library item",
    "BOOM": "Explosion sound",
    "BOOT": "Winter footwear",
    "BORN": "Arrived into the world",
    "BOSS": "Office superior",
    "BOTH": "Not one, not the other, but",
    "BOWL": "Cereal container",
    "BULB": "Light fixture part",
    "BURN": "Sunbather's risk",
    "BUSY": "Not free",
    "CAFE": "Coffee shop",
    "CAGE": "Bird's home",
    "CAKE": "Birthday dessert",
    "CALF": "Baby cow",
    "CALL": "Ring someone up",
    "CALM": "Peaceful",
    "CAMP": "Summer getaway with tents",
    "CAPE": "Superhero's accessory",
    "CARD": "Birthday greeting",
    "CARE": "Look after",
    "CASE": "Court matter, or a suitcase",
    "CASH": "Paper money",
    "CAST": "Broken arm's covering",
    "CAVE": "Bat's home",
    "CELL": "Prison room, or a phone type",
    "CHAT": "Casual talk",
    "CHEF": "Kitchen boss",
    "CHIN": "Below the mouth",
    "CITY": "Urban area",
    "CLAM": "Shellfish that clams up",
    "CLAP": "Applause sound",
    "CLAY": "Pottery material",
    "CLUB": "Golf tool, or a nightlife venue",
    "COAL": "Fossil fuel, black",
    "COAT": "Winter layer",
    "CODE": "Programmer's language",
    "COIN": "Vending machine's need",
    "COLD": "Winter weather",
    "COOK": "Kitchen worker",
    "COOL": "Not warm",
    "CORE": "Apple's center",
    "CORN": "Cob crop",
    "COST": "Price tag",
    "CREW": "Ship's team",
    "CROP": "Farmer's harvest",
    "CUBE": "Ice's shape",
    "CURB": "Sidewalk's edge",
    "CURE": "Illness fix",
    "DARE": "Truth or ___",
    "DARK": "Not light",
    "DATA": "Spreadsheet's contents",
    "DATE": "Calendar entry, or a fruit",
    "DAWN": "Sunrise",
    "DEAL": "Business agreement",
    "DEBT": "Money owed",
    "DECK": "Ship's floor, or a card set",
    "DEEP": "Not shallow",
    "DEER": "Headlight starer",
    "DENY": "Refuse to admit",
    "DESK": "Office furniture",
    "DIAL": "Old phone's spinner",
    "DIET": "Eating plan",
    "DIRT": "Garden soil",
    "DISH": "Dinner plate",
    "DOOR": "Room's entrance",
    "DOSE": "Medicine amount",
    "DOWN": "Not up",
    "DRAW": "Tie score, or sketch",
    "DREW": "Past tense of draw",
    "DROP": "Let fall",
    "DRUM": "Beat this to keep time",
    "DUCK": "Pond bird",
    "DULL": "Not sharp",
    "DUMP": "Trash site",
    "DUST": "Furniture's fine enemy",
    "EACH": "Every single one",
    "EARN": "Work for a paycheck",
    "EASE": "Take it easy",
    "EAST": "Sunrise direction",
    "EASY": "Not hard",
    "ECHO": "Canyon's reply",
    "EDGE": "Cliff's rim",
    "EPIC": "Grand in scale",
    "EVEN": "Not odd",
    "EVIL": "Villain's trait",
    "EXIT": "Way out",
    "FACE": "Front of the head",
    "FACT": "Verified truth",
    "FAIR": "County event, or just",
    "FALL": "Autumn",
    "FARM": "Where crops grow",
    "FAST": "Speedy",
    "FATE": "Destiny",
    "FEAR": "Fright",
    "FEED": "Give food to",
    "FEEL": "Sense by touch",
    "FILE": "Folder's contents",
    "FILL": "Top off the tank",
    "FILM": "Movie",
    "FIND": "Locate",
    "FINE": "OK, or a parking ticket",
    "FIRE": "Campfire's blaze",
    "FIRM": "Sturdy, or a company",
    "FISH": "Aquarium resident",
    "FIST": "Closed hand",
    "FIVE": "Half of ten",
    "FLAG": "Nation's banner",
    "FLAT": "Not hilly, or a punctured tire",
    "FLIP": "Coin's toss",
    "FLOW": "River's motion",
    "FOLD": "Origami move",
    "FOOD": "What you eat",
    "FOOT": "Twelve inches",
    "FORK": "Salad's utensil",
    "FORM": "Shape, or paperwork",
    "FORT": "Kids' backyard hideout",
    "FOUR": "One less than five",
    "FREE": "No cost",
    "FROG": "Lily pad sitter",
    "FUEL": "Gas tank's contents",
    "FULL": "Not empty",
    "FUND": "Money pool",
    "GAIN": "Increase",
    "GAME": "Board or video pastime",
    "GATE": "Airport boarding area",
    "GAVE": "Past tense of give",
    "GAZE": "Long stare",
    "GEAR": "Bike's speed setting, or equipment",
    "GENE": "DNA unit",
    "GIFT": "Wrapped present",
    "GLOW": "Soft light",
    "GOAL": "Soccer's target",
    "GOAT": "Barnyard climber",
    "GOLD": "Olympic medal color",
    "GOLF": "Sport with a tee",
    "GONE": "No longer here",
    "GOOD": "Not bad",
    "GRAY": "Overcast sky's shade",
    "GREW": "Past tense of grow",
    "GRID": "Crossword's frame",
    "GRIN": "Wide smile",
    "GROW": "Get taller",
    "GULF": "Body of water, or a big gap",
    "HAIR": "Barber's business",
    "HALF": "Fifty percent",
    "HALL": "School corridor",
    "HAND": "Watch's pointer",
    "HARD": "Not soft",
    "HARM": "Do damage",
    "HAWK": "Sharp-eyed bird",
    "HEAD": "Body's top",
    "HEAL": "Wound's job",
    "HEAP": "Pile",
    "HEAR": "Perceive sound",
    "HEAT": "Summer's discomfort",
    "HELD": "Past tense of hold",
    "HELP": "Lend a hand",
    "HERB": "Basil, for one",
    "HERE": "Not there",
    "HERO": "Story's protagonist",
    "HIDE": "Play ___ and seek",
    "HIGH": "Not low",
    "HIKE": "Trail walk",
    "HILL": "Small mound",
    "HINT": "Small clue",
    "HIRE": "Give a job to",
    "HOLD": "Grip",
    "HOLE": "Golf's target",
    "HOME": "Where the heart is",
    "HONK": "Car horn's sound",
    "HOOK": "Fishing line's end",
    "HOPE": "Optimistic wish",
    "HORN": "Car's beeper",
    "HOST": "Party thrower",
    "HOUR": "Sixty minutes",
    "HUGE": "Enormous",
    "HUNT": "Search for game",
    "HURT": "Cause pain",
    "ICON": "App's tiny picture",
    "IDEA": "Lightbulb moment",
    "INCH": "Twelfth of a foot",
    "INTO": "Toward the inside of",
    "IRON": "Wrinkle remover",
    "ITEM": "Single thing on a list",
    "JAZZ": "Improvised music genre",
    "JEAN": "Denim, singular",
    "JOIN": "Sign up",
    "JOKE": "Setup for a punchline",
    "JUMP": "Hop",
    "JURY": "Court's decision makers",
    "JUST": "Merely, or fair",
    "KEEP": "Hold onto",
    "KICK": "Soccer's main move",
    "KIND": "Nice, or a type",
    "KING": "Chess piece that can't be captured",
    "KISS": "Peck on the cheek",
    "KNEE": "Leg's bendy joint",
    "KNOT": "Boy Scout's tie",
    "LACE": "Shoe's tie",
    "LACK": "Shortage",
    "LAKE": "Freshwater basin",
    "LAMB": "Baby sheep",
    "LAMP": "Bedside light",
    "LAND": "Solid ground",
    "LANE": "Bowling alley's alley",
    "LATE": "Not on time",
    "LAWN": "Yard's grass",
    "LEAD": "Race's front spot, or a metal",
    "LEAF": "Tree's autumn dropper",
    "LEAN": "Not fatty",
    "LEFT": "Not right",
    "LEND": "Loan out",
    "LESS": "Not as much",
    "LIFE": "Existence",
    "LIFT": "Elevator's job",
    "LIKE": "Enjoy",
    "LIME": "Green citrus",
    "LINE": "Queue",
    "LINK": "Chain's unit",
    "LION": "King of the jungle",
    "LIST": "Grocery run's guide",
    "LIVE": "Broadcast in real time",
    "LOAD": "Truck's cargo",
    "LOAN": "Borrowed money",
    "LOCK": "Key's target",
    "LONG": "Not short",
    "LOOK": "Take a glance",
    "LOOP": "Rollercoaster's twist",
    "LORD": "Manor's owner",
    "LOSE": "Not win",
    "LOSS": "Defeat",
    "LOUD": "Not quiet",
    "LOVE": "Tennis's zero, or deep affection",
    "LUCK": "Four-leaf clover's promise",
    "LUNG": "Breathing organ",
    "MAIL": "Postal delivery",
    "MAIN": "Primary",
    "MAKE": "Create",
    "MALE": "Not female",
    "MANY": "A lot",
    "MARK": "Grade, or a scuff",
    "MASK": "Halloween essential",
    "MEAL": "Breakfast, lunch, or dinner",
    "MEAN": "Unkind, or an average",
    "MEAT": "Butcher's stock",
    "MEET": "Get together",
    "MELT": "Ice cream in the sun",
    "MENU": "Restaurant's list",
    "MESS": "Cluttered room",
    "MICE": "Plural of mouse",
    "MILD": "Not too spicy",
    "MILE": "5,280 feet",
    "MILK": "Cereal's companion",
    "MIND": "Brain's domain",
    "MINE": "My own, or an explosive",
    "MINT": "Fresh breath candy",
    "MISS": "Miscalculate, or unmarried title",
    "MIST": "Light fog",
    "MOOD": "Emotional state",
    "MOON": "Night sky's satellite",
    "MORE": "Additional",
    "MOSS": "Damp rock's carpet",
    "MOST": "Majority",
    "MOVE": "Change position",
    "MUCH": "A great deal",
    "MUST": "Have to",
    "NAIL": "Hammer's target",
    "NAME": "What you're called",
    "NEAR": "Close by",
    "NECK": "Head's support",
    "NEST": "Bird's home",
    "NEWS": "Daily headlines",
    "NEXT": "Following",
    "NICE": "Kind",
    "NINE": "One less than ten",
    "NOON": "Midday",
    "NOSE": "Smell's organ",
    "NOTE": "Sticky reminder",
    "ONLY": "Sole",
    "OPEN": "Not closed",
    "ORAL": "Spoken",
    "OVAL": "Egg's shape",
    "OVEN": "Bakes the cake",
    "OVER": "Above, or finished",
    "PACE": "Walking speed",
    "PACK": "Backpack's contents",
    "PAGE": "Book's leaf",
    "PAID": "Settled the bill",
    "PAIN": "Discomfort",
    "PAIR": "Two of a kind",
    "PALE": "Lacking color",
    "PARK": "Playground's setting",
    "PART": "Piece of the whole",
    "PASS": "Football's throw",
    "PAST": "Before now",
    "PATH": "Trail",
    "PEAK": "Mountain's top",
    "PEEL": "Banana's skin",
    "PICK": "Choose",
    "PILE": "Stack",
    "PINK": "Flamingo's color",
    "PLAN": "Blueprint",
    "PLAY": "Have fun",
    "PLOT": "Story's arc, or a garden patch",
    "PLUG": "Outlet's mate",
    "PLUS": "Addition sign",
    "POEM": "Rhyming verse, maybe",
    "POET": "Verse writer",
    "POKE": "Nudge",
    "POLE": "Flagpole's frame",
    "POND": "Backyard's small lake",
    "POOL": "Backyard swim spot",
    "POOR": "Lacking money",
    "PORT": "Harbor",
    "POSE": "Yoga's move",
    "POST": "Fence's upright, or a social share",
    "PULL": "Tug",
    "PUMP": "Gas station's dispenser",
    "PURE": "Not mixed",
    "PUSH": "Shove",
    "QUIT": "Give up",
    "RACE": "Speed contest",
    "RAIL": "Train's track",
    "RAIN": "Umbrella's reason",
    "RANK": "Military grade",
    "RARE": "Not well-done, or scarce",
    "RATE": "Interest percentage",
    "READ": "Book's activity",
    "REAL": "Not fake",
    "REST": "Take a break",
    "RICE": "Sushi's base",
    "RICH": "Wealthy",
    "RIDE": "Amusement park draw",
    "RING": "Wedding jewelry",
    "RISE": "Sun's morning move",
    "RISK": "Gamble",
    "ROAD": "Highway",
    "ROAR": "Lion's greeting",
    "ROCK": "Guitar genre, or a stone",
    "ROLE": "Actor's part",
    "ROLL": "Bread's small loaf",
    "ROOF": "House's top",
    "ROOM": "Bedroom, e.g.",
    "ROOT": "Tree's underground anchor",
    "ROPE": "Tug of war's tool",
    "ROSE": "Valentine's flower",
    "RUDE": "Not polite",
    "RULE": "Game's guideline",
    "RUSH": "Hurry",
    "SAFE": "Not risky",
    "SAIL": "Boat's wind catcher",
    "SALE": "Discount event",
    "SALT": "Fry's companion",
    "SAME": "Identical",
    "SAND": "Beach's texture",
    "SAVE": "Put money aside",
    "SEAT": "Chair's purpose",
    "SEED": "Sunflower's start",
    "SEEK": "Hide and ___",
    "SEEM": "Appear to be",
    "SELF": "One's own person",
    "SELL": "Opposite of buy",
    "SEND": "Mail off",
    "SENT": "Past tense of send",
    "SHIP": "Ocean vessel",
    "SHOE": "Foot's cover",
    "SHOP": "Store",
    "SHOT": "Basketball's attempt",
    "SHOW": "TV program",
    "SIDE": "Not the middle",
    "SIGN": "Billboard's message",
    "SILK": "Smooth fabric",
    "SING": "Karaoke's activity",
    "SIZE": "Shirt's measurement",
    "SKIN": "Body's outer layer",
    "SLOW": "Not fast",
    "SNAP": "Quick photo, or a finger click",
    "SNOW": "Winter's white blanket",
    "SOAP": "Shower's lather",
    "SOCK": "Foot's inner layer",
    "SOFA": "Living room seat",
    "SOFT": "Not hard",
    "SOIL": "Garden's dirt",
    "SOLD": "Past tense of sell",
    "SONG": "Radio's tune",
    "SOON": "Not long from now",
    "SORT": "Organize",
    "SOUL": "Music genre, or spirit",
    "SOUP": "Warm bowlful",
    "SPIN": "Washing machine's cycle",
    "SPOT": "Dalmatian's marking",
    "STAR": "Night sky's twinkle",
    "STAY": "Remain",
    "STEM": "Flower's stalk",
    "STEP": "Stair's unit",
    "STOP": "Traffic sign's command",
    "SUCH": "Of that kind",
    "SUIT": "Boardroom attire",
    "SURE": "Confident",
    "SWIM": "Pool's activity",
    "TAIL": "Dog's wagger",
    "TAKE": "Grab",
    "TALE": "Bedtime story",
    "TALK": "Chat",
    "TALL": "Not short",
    "TANK": "Fish's glass home",
    "TAPE": "Sticky roll",
    "TASK": "Chore",
    "TEAM": "Sports group",
    "TEAR": "Rip, or a sad drop",
    "TELL": "Reveal",
    "TENT": "Camping shelter",
    "TERM": "School semester",
    "TEST": "Pop quiz",
    "TEXT": "Phone message",
    "THAN": "Comparison word",
    "THAT": "Not this",
    "THEM": "Not us",
    "THEN": "After that",
    "THIN": "Not thick",
    "THIS": "Not that",
    "TIDE": "Ocean's rise and fall",
    "TILE": "Bathroom floor piece",
    "TIME": "Clock's measure",
    "TINY": "Very small",
    "TIRE": "Car's wheel cover",
    "TOLD": "Past tense of tell",
    "TONE": "Voice's quality",
    "TOOK": "Past tense of take",
    "TOOL": "Hammer, for one",
    "TOUR": "Guided visit",
    "TOWN": "Small city",
    "TRAY": "Cafeteria carrier",
    "TREE": "Backyard shade giver",
    "TRIM": "Haircut's light version",
    "TRIP": "Vacation",
    "TRUE": "Not false",
    "TUNE": "Melody",
    "TURN": "Steering wheel's job",
    "TWIN": "Identical sibling",
    "TYPE": "Keyboard's action",
    "UGLY": "Not pretty",
    "UNIT": "Single measure",
    "UPON": "On top of",
    "USED": "Not new",
    "VAIN": "Overly proud",
    "VAST": "Enormous in scope",
    "VEIN": "Blood's pathway",
    "VERY": "Extremely",
    "VIEW": "Scenic overlook",
    "VOTE": "Ballot's action",
    "WAGE": "Hourly pay",
    "WAIT": "Stand in line",
    "WAKE": "Alarm's job",
    "WALK": "Stroll",
    "WALL": "Room's boundary",
    "WANT": "Desire",
    "WARM": "Not cold",
    "WASH": "Laundry's action",
    "WAVE": "Ocean's motion, or a hello",
    "WEAR": "Put on clothes",
    "WEEK": "Seven days",
    "WELL": "Water source, or in good health",
    "WENT": "Past tense of go",
    "WEST": "Sunset direction",
    "WHAT": "Question word",
    "WHEN": "Time question word",
    "WIDE": "Not narrow",
    "WIFE": "Husband's partner",
    "WILD": "Untamed",
    "WIND": "Kite's power source",
    "WINE": "Grape's aged drink",
    "WING": "Bird's flight tool",
    "WIRE": "Electrician's material",
    "WISE": "Owl-like, smart",
    "WISH": "Birthday candle's purpose",
    "WOOD": "Log cabin's material",
    "WOOL": "Sheep's coat",
    "WORD": "This puzzle is full of them",
    "WORE": "Past tense of wear",
    "WORK": "Nine-to-five",
    "YARD": "Backyard's measure, three feet",
    "YEAR": "Twelve months",
    "ZERO": "Nothing, or love in tennis",
    "ZONE": "End ___, football's goal area",
    "ZOOM": "Video call app, or speed off",
}

WORDS_5 = {
    "ABOUT": "Roughly, or a topic's subject",
    "ABOVE": "Higher than",
    "ADULT": "Grown-up",
    "AFTER": "Following",
    "AGAIN": "One more time",
    "AGENT": "Spy, or a Hollywood dealmaker",
    "AGREE": "See eye to eye",
    "AHEAD": "In front",
    "ALARM": "Wake-up sound",
    "ALBUM": "Record collection",
    "ALIVE": "Not dead",
    "ALLOW": "Permit",
    "ALONE": "Solo",
    "ALONG": "In line with",
    "ALTER": "Change",
    "AMONG": "In the midst of",
    "ANGEL": "Halo wearer",
    "ANGER": "Rage",
    "ANGLE": "Corner's measure",
    "ANGRY": "Fuming",
    "ANKLE": "Foot's hinge",
    "APPLE": "Teacher's classic gift",
    "APPLY": "Submit an application",
    "APRON": "Chef's cover-up",
    "ARENA": "Sports venue",
    "ARGUE": "Bicker",
    "ARISE": "Come up",
    "ARROW": "Bow's ammo",
    "ASIDE": "To the side, or a stage whisper",
    "ASKED": "Requested",
    "ASSET": "Valuable resource",
    "AVOID": "Steer clear of",
    "AWAIT": "Wait for",
    "AWARD": "Trophy",
    "AWFUL": "Terrible",
    "BADLY": "Poorly",
    "BAKER": "Bread maker",
    "BASIC": "Fundamental",
    "BASIN": "Sink's bowl",
    "BEACH": "Sandy shore",
    "BEGAN": "Started",
    "BEGIN": "Start",
    "BELOW": "Under",
    "BENCH": "Park seat",
    "BIRTH": "Baby's arrival",
    "BLACK": "Night's color",
    "BLADE": "Fan's spinning part",
    "BLAME": "Point the finger",
    "BLANK": "Empty space to fill in",
    "BLAST": "Explosion, or a great time",
    "BLEND": "Mix together",
    "BLESS": "Say a prayer over",
    "BLIND": "Sightless",
    "BLOCK": "Building material, or a city stretch",
    "BLOOD": "Vampire's diet",
    "BOARD": "Chess's playing surface",
    "BOAST": "Brag",
    "BONUS": "Extra reward",
    "BOOST": "Increase",
    "BOUND": "Destined, or a leap",
    "BRAIN": "Body's thinking organ",
    "BRAND": "Company's label",
    "BREAD": "Toast's raw form",
    "BREAK": "Recess",
    "BRICK": "House's building block",
    "BRIEF": "Short and to the point",
    "BRING": "Carry over",
    "BROAD": "Wide",
    "BROWN": "Chocolate's shade",
    "BRUSH": "Toothpaste's partner",
    "BUILD": "Construct",
    "BUNCH": "Group of bananas",
    "CABIN": "Woodsy retreat",
    "CANDY": "Halloween haul",
    "CARGO": "Ship's freight",
    "CATCH": "Fielder's job",
    "CAUSE": "Reason",
    "CHAIN": "Bike's driving link",
    "CHAIR": "Desk's companion",
    "CHALK": "Chalkboard's tool",
    "CHARM": "Bracelet's dangling piece",
    "CHASE": "Cops and robbers game",
    "CHEAP": "Not expensive",
    "CHECK": "Restaurant's bill",
    "CHEST": "Ribcage's front",
    "CHIEF": "Top boss",
    "CHILD": "Kid",
    "CHUNK": "Big piece",
    "CIVIL": "Polite, or nonmilitary",
    "CLAIM": "Insurance's request",
    "CLASS": "School period",
    "CLEAN": "Not dirty",
    "CLEAR": "Sky after the storm",
    "CLERK": "Store's checkout worker",
    "CLICK": "Mouse's sound",
    "CLIMB": "Ladder's activity",
    "CLOCK": "Time teller",
    "CLOSE": "Shut, or nearby",
    "CLOTH": "Fabric",
    "CLOUD": "Sky's puffy shape",
    "COACH": "Team's leader",
    "COAST": "Shoreline",
    "COLOR": "Crayon's job",
    "COUCH": "Living room's seat",
    "COUGH": "Cold's symptom",
    "COULD": "Might have",
    "COUNT": "Tally up",
    "COVER": "Book's front",
    "CRACK": "Sidewalk's flaw",
    "CRAFT": "Handmade project",
    "CRASH": "Fender bender",
    "CRAZY": "Wild, or nuts",
    "CREAM": "Coffee's lightener",
    "CREEK": "Small stream",
    "CRIME": "Detective's case",
    "CROSS": "Bad-tempered, or a plus-sign shape",
    "CROWD": "Concert's audience",
    "CROWN": "King's headwear",
    "CRUEL": "Unkind, deeply",
    "CRUSH": "Secret admiration",
    "DAILY": "Every day",
    "DANCE": "Prom's activity",
    "DEATH": "Life's end",
    "DELAY": "Flight's setback",
    "DEPTH": "How deep",
    "DIRTY": "Not clean",
    "DOUBT": "Uncertainty",
    "DOZEN": "A round twelve",
    "DRAFT": "Rough first version",
    "DRAIN": "Sink's outlet",
    "DRAMA": "Soap opera's genre",
    "DRESS": "Formal wear for a night out",
    "DRIED": "No longer wet",
    "DRINK": "Beverage",
    "DRIVE": "Road trip's activity",
    "EAGER": "Enthusiastic",
    "EARLY": "Not late",
    "EARTH": "Third rock from the sun",
    "EIGHT": "One less than nine",
    "ELBOW": "Arm's bend",
    "EMPTY": "Nothing inside",
    "ENJOY": "Have a great time",
    "ENTER": "Go inside",
    "ENTRY": "Doorway",
    "EQUAL": "Same amount",
    "ERROR": "Coding bug",
    "EVENT": "Scheduled happening",
    "EVERY": "Each one",
    "EXACT": "Precise",
    "EXIST": "Be real",
    "EXTRA": "Bonus",
    "FAINT": "Barely there, or to pass out",
    "FAIRY": "Wand-waving story character",
    "FAITH": "Trust, deep down",
    "FALSE": "Not true",
    "FANCY": "Upscale",
    "FEWER": "Not as many",
    "FIELD": "Farmer's crop land",
    "FIFTH": "After fourth",
    "FIFTY": "Half a hundred",
    "FIGHT": "Boxing match",
    "FINAL": "Last",
    "FIRST": "Not second",
    "FIXED": "Repaired",
    "FLAME": "Candle's tip",
    "FLOOD": "Overflowing river",
    "FLOOR": "Room's base",
    "FLOUR": "Bread's main ingredient",
    "FOCUS": "Concentrate",
    "FORCE": "Push or pull",
    "FORTH": "Onward",
    "FORTY": "Four times ten",
    "FOUND": "Located",
    "FRAME": "Picture's border",
    "FRESH": "Just made",
    "FRONT": "Not the back",
    "FROST": "Winter's icy coat",
    "FRUIT": "Apple or banana",
    "FUNNY": "Comedy's goal",
    "GHOST": "Halloween's spooky spirit",
    "GIANT": "Jack's beanstalk foe",
    "GIVEN": "Provided",
    "GLASS": "Window's material",
    "GLOBE": "World map, spherical",
    "GOING": "In motion toward",
    "GRADE": "Report card's letter",
    "GRAND": "Impressive, or a thousand dollars",
    "GRANT": "Award money for research",
    "GRASS": "Lawn's cover",
    "GREAT": "Excellent",
    "GREEN": "Grass's color",
    "GRIEF": "Deep sorrow",
    "GROSS": "Disgusting, or a total before deductions",
    "GROUP": "Team, essentially",
    "GROWN": "Matured",
    "GUARD": "Protect",
    "GUESS": "Educated estimate",
    "GUEST": "Party's invitee",
    "GUIDE": "Tour leader",
    "HAPPY": "Content",
    "HARSH": "Overly critical",
    "HASTE": "Rushed speed",
    "HEART": "Valentine's symbol",
    "HEAVY": "Not light",
    "HELLO": "Greeting",
    "HONEY": "Bee's sweet output",
    "HORSE": "Stable's resident",
    "HOTEL": "Overnight stay spot",
    "HOUSE": "Home",
    "HUMAN": "Person",
    "HUMOR": "Sense of funny",
    "IDEAL": "Perfect",
    "IMAGE": "Picture",
    "INDEX": "Book's back-of-page list",
    "INNER": "Not outer",
    "INPUT": "Data you type in",
    "ISSUE": "Problem, or a magazine copy",
    "JOINT": "Elbow or knee",
    "JUDGE": "Courtroom's decider",
    "JUICE": "Orange's liquid",
    "KNIFE": "Butter's spreader",
    "KNOCK": "Door's greeting",
    "LABEL": "Jar's sticker",
    "LARGE": "Big",
    "LASER": "Focused light beam",
    "LATER": "Not now",
    "LAUGH": "Ha ha",
    "LEARN": "Pick up a new skill",
    "LEAST": "Smallest amount",
    "LEAVE": "Head out",
    "LEMON": "Sour yellow fruit",
    "LEVEL": "Flat, or a video game stage",
    "LIGHT": "Not heavy, or not dark",
    "LIMIT": "Speed's ceiling",
    "LOCAL": "Nearby, not chain",
    "LOGIC": "Reasoned thinking",
    "LOOSE": "Not tight",
    "LOWER": "Bring down",
    "LOYAL": "Faithful",
    "LUNCH": "Midday meal",
    "MAGIC": "Wand's specialty",
    "MAJOR": "College's chosen field",
    "MEDIA": "News outlets, collectively",
    "MERGE": "Traffic lanes combining",
    "MERIT": "Deserved credit",
    "METAL": "Iron or steel",
    "MIGHT": "Could possibly",
    "MINOR": "Small, or under 18",
    "MODEL": "Runway walker",
    "MONEY": "Cash",
    "MONTH": "Thirty-ish days",
    "MORAL": "Story's lesson",
    "MOTOR": "Engine",
    "MOUNT": "Climb up",
    "MOUSE": "Cat's chase target",
    "MOUTH": "Where you eat",
    "MOVIE": "Cinema's offering",
    "MUSIC": "Radio's content",
    "NAKED": "Bare, unclothed",
    "NASTY": "Mean-spirited",
    "NAVAL": "Relating to the navy",
    "NERVE": "Guts, or a body signal",
    "NEVER": "Not once",
    "NIGHT": "Not day",
    "NOBLE": "Honorable",
    "NOISE": "Loud racket",
    "NORTH": "Compass's top",
    "NOVEL": "Full-length book",
    "NURSE": "Hospital's caregiver",
    "OCEAN": "Vast body of saltwater",
    "OFFER": "Job's proposal",
    "OFTEN": "Frequently",
    "ORDER": "Restaurant's request",
    "OTHER": "Not this one",
    "OUGHT": "Should",
    "OUTER": "Not inner",
    "OWNER": "Property's holder",
    "PANEL": "Discussion group",
    "PAPER": "Printer's supply",
    "PARTY": "Birthday bash",
    "PASTA": "Spaghetti, broadly",
    "PATCH": "Repair spot",
    "PAUSE": "Remote's stop button",
    "PEACE": "Calm, no conflict",
    "PHASE": "Moon's stage",
    "PHONE": "Pocket device",
    "PHOTO": "Snapshot",
    "PIANO": "88-key instrument",
    "PIECE": "Puzzle's unit",
    "PILOT": "Plane's flyer",
    "PITCH": "Baseball's throw, or a sales speech",
    "PLACE": "Location",
    "PLAIN": "Not fancy",
    "PLANE": "Sky's traveler",
    "PLANT": "Garden's green resident",
    "PLATE": "Dinner's dish",
    "POINT": "Sharp end, or a score",
    "POUND": "Sixteen ounces",
    "POWER": "Energy",
    "PRESS": "News media, or to iron",
    "PRICE": "Tag's number",
    "PRIDE": "Lion's group, or self-respect",
    "PRIME": "Best, or unfactorable",
    "PRINT": "Newspaper's fine text",
    "PRIOR": "Beforehand",
    "PRIZE": "Contest's reward",
    "PROOF": "Evidence",
    "PROUD": "Beaming with satisfaction",
    "PULSE": "Heartbeat's rhythm",
    "PUPIL": "Eye's black center, or a student",
    "QUEEN": "Chess piece with the most moves",
    "QUICK": "Fast",
    "QUIET": "Library's rule",
    "QUITE": "Rather",
    "RADIO": "Car's music source",
    "RAISE": "Salary bump",
    "RANGE": "Stove, or a mountain chain",
    "RAPID": "Swift",
    "RATIO": "Comparison of two numbers",
    "REACH": "Extend an arm",
    "READY": "Prepared",
    "REALM": "Kingdom",
    "REBEL": "Cause defier",
    "RECAP": "Quick summary",
    "RELAX": "Kick back",
    "REPLY": "Answer",
    "RIGHT": "Not left, or correct",
    "RIVAL": "Competitor",
    "RIVER": "Flowing waterway",
    "ROBOT": "Mechanical worker",
    "ROUGH": "Not smooth",
    "ROUND": "Not square",
    "ROUTE": "Path taken",
    "ROYAL": "Fit for a king",
    "RUGBY": "Football's British cousin",
    "RUMOR": "Unverified gossip",
    "SALAD": "Leafy side dish",
    "SAUCE": "Pasta's topping",
    "SCALE": "Weight's measurer",
    "SCARE": "Halloween's goal",
    "SCENE": "Movie's segment",
    "SCOPE": "Range, or a rifle's sight",
    "SCORE": "Game's tally",
    "SENSE": "Common ___",
    "SEVEN": "Lucky number",
    "SHADE": "Tree's cool spot",
    "SHAKE": "Milkshake's action",
    "SHAPE": "Circle or square",
    "SHARE": "Split with a friend",
    "SHARP": "Not dull",
    "SHEEP": "Wool's source",
    "SHEET": "Bed's cover",
    "SHELF": "Bookcase's tier",
    "SHELL": "Beach's souvenir",
    "SHIFT": "Work schedule's block",
    "SHINE": "Sunlight's action",
    "SHIRT": "Button-up top",
    "SHOCK": "Sudden surprise",
    "SHORT": "Not tall",
    "SHOUT": "Yell",
    "SIGHT": "One of the five senses",
    "SILLY": "Goofy",
    "SINCE": "From that point on",
    "SIXTH": "After fifth",
    "SKILL": "Learned ability",
    "SLEEP": "Nightly rest",
    "SLICE": "Pizza's serving",
    "SLIDE": "Playground's chute",
    "SMALL": "Not big",
    "SMART": "Sharp-minded",
    "SMELL": "Nose's job",
    "SMILE": "Happy expression",
    "SMOKE": "Fire's byproduct",
    "SNAKE": "Legless reptile",
    "SOLID": "Not liquid or gas",
    "SOLVE": "Crack the puzzle",
    "SORRY": "Apology's word",
    "SOUND": "Speaker's output",
    "SOUTH": "Compass's bottom",
    "SPACE": "Room, or the final frontier",
    "SPARE": "Extra tire",
    "SPEAK": "Say out loud",
    "SPEED": "Highway's limit",
    "SPELL": "Witch's incantation",
    "SPEND": "Shell out money",
    "SPICE": "Curry's kick",
    "SPLIT": "Divide evenly",
    "SPORT": "Football or tennis",
    "SPRAY": "Perfume's mist",
    "STACK": "Pile of pancakes",
    "STAFF": "Office's employees",
    "STAGE": "Concert's platform",
    "STAIR": "Step on a staircase",
    "STAMP": "Envelope's postage",
    "STAND": "Take a position",
    "STARE": "Long, fixed look",
    "START": "Race's beginning",
    "STATE": "Country's division",
    "STEAK": "Grilled beef cut",
    "STEAL": "Take without asking",
    "STEEL": "Skyscraper's frame",
    "STICK": "Fetch's toy",
    "STIFF": "Not flexible",
    "STOCK": "Supply on hand",
    "STONE": "Rock",
    "STORE": "Shop",
    "STORM": "Thunder and lightning",
    "STORY": "Bedtime tale",
    "STOVE": "Kitchen's cooktop",
    "STUDY": "Hit the books",
    "STUFF": "Belongings",
    "STYLE": "Fashion sense",
    "SUGAR": "Sweetener",
    "SUPER": "Awesome",
    "SWEAT": "Workout's byproduct",
    "SWEET": "Not sour",
    "SWIFT": "Fast, like an arrow",
    "SWING": "Playground favorite",
    "TABLE": "Dinner's surface",
    "TASTE": "Tongue's job",
    "TEACH": "Pass on knowledge",
    "THANK": "Say gratitude",
    "THEIR": "Belonging to them",
    "THERE": "Not here",
    "THICK": "Not thin",
    "THING": "Object",
    "THINK": "Ponder",
    "THIRD": "After second",
    "THOSE": "Plural of that",
    "THREE": "One more than two",
    "THREW": "Past tense of throw",
    "THUMB": "Hitchhiker's digit",
    "TIGER": "Striped big cat",
    "TIGHT": "Not loose",
    "TIRED": "In need of sleep",
    "TITLE": "Book's name",
    "TODAY": "This very date",
    "TOOTH": "Dentist's focus",
    "TOTAL": "Grand sum",
    "TOUCH": "Fifth sense",
    "TOUGH": "Hard to break",
    "TOWEL": "Beach's drying cloth",
    "TOWER": "Skyscraper's shape",
    "TRACK": "Runner's oval",
    "TRADE": "Swap",
    "TRAIL": "Hiking path",
    "TRAIN": "Subway's cousin",
    "TREAT": "Dog's reward",
    "TREND": "Fashion's fad",
    "TRIAL": "Courtroom's proceeding",
    "TRICK": "Magician's specialty",
    "TRUCK": "Pickup or big rig",
    "TRULY": "Genuinely",
    "TRUST": "Faith in someone",
    "TRUTH": "Not a lie",
    "TWICE": "Two times",
    "UNCLE": "Dad's brother",
    "UNDER": "Below",
    "UNION": "Workers' collective",
    "UNTIL": "Up to the point that",
    "UPPER": "Not lower",
    "URBAN": "City-related",
    "USUAL": "Normal",
    "VALID": "Legitimate",
    "VALUE": "Worth",
    "VIDEO": "Streaming site's content",
    "VISIT": "Drop by",
    "VOICE": "Singer's instrument",
    "WASTE": "Trash, or squander",
    "WATCH": "Wrist's timepiece",
    "WATER": "H2O",
    "WHEAT": "Bread's grain",
    "WHEEL": "Car's roller",
    "WHERE": "Location question word",
    "WHICH": "Choice question word",
    "WHILE": "During the time that",
    "WHITE": "Snow's color",
    "WHOLE": "Entire",
    "WORLD": "Planet Earth",
    "WORRY": "Fret",
    "WORSE": "Not as good",
    "WORTH": "Value",
    "WOULD": "Conditional word",
    "WOUND": "Injury",
    "WRIST": "Watch's location",
    "WRITE": "Pen's job",
    "YOUNG": "Not old",
    "YOUTH": "Younger years",
}

# A second, larger pass of common 5-letter fill. A dense 5x5 needs far more
# crossing words than the first batch alone can carry; see the module
# docstring's proof that every entry in this grid shape is length 3 or 5.
WORDS_5.update({
    "ADMIT": "Confess",
    "ADOPT": "Take in a rescue pet",
    "ADORE": "Love deeply",
    "ALIGN": "Line up",
    "ALIKE": "Similar",
    "ALIEN": "UFO's occupant",
    "ALLOY": "Bronze, for one",
    "ALOFT": "Up in the air",
    "AMBER": "Fossilized tree resin",
    "AMPLE": "Plenty",
    "AMUSE": "Entertain",
    "ANNOY": "Bug",
    "ANVIL": "Blacksmith's block",
    "AROMA": "Bakery's inviting smell",
    "ATLAS": "Book of maps",
    "ATTIC": "House's top storage room",
    "AUDIO": "Sound recording",
    "AWAKE": "Not asleep",
    "BACON": "Breakfast strip",
    "BADGE": "Sheriff's star",
    "BAGGY": "Loose-fitting",
    "BASIL": "Pesto's herb",
    "BATCH": "Cookie's whole tray",
    "BATON": "Relay race's handoff",
    "BATTY": "A little crazy",
    "BEADY": "Small and shiny, like eyes",
    "BEEFY": "Muscular",
    "BERRY": "Blueberry, for one",
    "BERTH": "Ship's docking spot",
    "BIBLE": "Sacred book",
    "BINGO": "Numbers game, or a triumphant shout",
    "BLEAK": "Grim",
    "BLIMP": "Blump-shaped airship",
    "BLOAT": "Swell up",
    "BLOOM": "Flower's opening",
    "BLOWN": "Past participle of blow",
    "BLUES": "Melancholy music genre",
    "BLUFF": "Poker's fake-out",
    "BLUNT": "Not sharp, or overly direct",
    "BLURT": "Say without thinking",
    "BOGUS": "Fake",
    "BOOTH": "Voting station",
    "BOOZE": "Alcohol, casually",
    "BOSSY": "Overly controlling",
    "BOUGH": "Tree's branch",
    "BRACE": "Prepare for impact",
    "BRAKE": "Car's stopping pedal",
    "BRASS": "Trumpet's metal",
    "BRAVE": "Fearless",
    "BRAWL": "Bar fight",
    "BREED": "Dog's type",
    "BRIBE": "Under-the-table payoff",
    "BRIDE": "Wedding's star",
    "BRINK": "Edge of disaster",
    "BRISK": "Quick and cool",
    "BROIL": "Oven's top-heat setting",
    "BROKE": "Out of money",
    "BROOK": "Small stream",
    "BROOM": "Sweeper's tool",
    "BROTH": "Soup's base",
    "BRUTE": "Thug",
    "BUDDY": "Pal",
    "BUGGY": "Baby stroller, or infested",
    "BULKY": "Hard to carry, big",
    "BULLY": "Playground menace",
    "BUMPY": "Not smooth",
    "BUNNY": "Easter's mascot",
    "BURLY": "Big and strong",
    "BUYER": "Auction's winner",
    "CABLE": "TV's wire",
    "CACHE": "Hidden stash",
    "CADET": "Military academy's student",
    "CAMEO": "Brief celebrity appearance",
    "CANAL": "Panama's waterway",
    "CANOE": "Paddle boat",
    "CAROL": "Christmas song",
    "CARRY": "Tote",
    "CARVE": "Turkey's slicing job",
    "CATER": "Provide the party's food",
    "CEASE": "Stop",
    "CEDAR": "Fragrant closet wood",
    "CHAOS": "Total disorder",
    "CHART": "Bar graph",
    "CHEEK": "Blusher's spot",
    "CHEER": "Sideline shout",
    "CHESS": "Board game with a king and queen",
    "CHEWY": "Not crunchy",
    "CHILL": "Relax",
    "CHIME": "Doorbell's sound",
    "CHIRP": "Cricket's noise",
    "CHOIR": "Church's singers",
    "CHOKE": "Blow it under pressure",
    "CHORD": "Guitar's three-note strum",
    "CHORE": "Household task",
    "CHOSE": "Past tense of choose",
    "CHUTE": "Laundry's drop tube",
    "CIGAR": "Rolled tobacco leaf",
    "CINCH": "A sure thing",
    "CIRCA": "Approximately, in dates",
    "CLAMP": "Woodworking's grip tool",
    "CLASP": "Necklace's fastener",
    "CLEFT": "Split down the middle",
    "CLIFF": "Sheer drop",
    "CLING": "Hold on tight",
    "CLINK": "Toast's glass sound",
    "CLONE": "Genetic copy",
    "CLOAK": "Cape",
    "CLOUT": "Influence",
    "CLOVE": "Warm baking spice",
    "CLOWN": "Circus's face-painted act",
    "CLUNK": "Dull thud",
    "COBRA": "Hooded venomous snake",
    "COCOA": "Hot chocolate's powder",
    "CODED": "Written in a programming language",
    "COMET": "Icy space traveler with a tail",
    "COMFY": "Cozy",
    "COMIC": "Funny, or a strip of panels",
    "CORAL": "Reef's living rock",
    "CORNY": "Cheesy, joke-wise",
    "COURT": "Basketball's playing surface",
    "COVEN": "Witches' gathering",
    "COVET": "Want badly",
    "COWER": "Shrink back in fear",
    "CRAMP": "Muscle's painful knot",
    "CRANE": "Construction site's lifter",
    "CRANK": "Turn a handle, or a grump",
    "CRAVE": "Want intensely",
    "CRAWL": "Baby's early move",
    "CREAK": "Old floorboard's sound",
    "CREPE": "Thin French pancake",
    "CREST": "Wave's peak, or a family emblem",
    "CRIMP": "Put a wave in your hair",
    "CRISP": "Freshly cool, or crunchy",
    "CROOK": "Con artist",
    "CRUMB": "Cookie's leftover speck",
    "CRUST": "Pizza's edge",
    "CUBIC": "Volume's measurement style",
    "CURLY": "Not straight, hairwise",
    "CURRY": "Spicy Indian dish",
    "CURVE": "Road's bend",
    "CYCLE": "Repeating pattern, or a bike ride",
    "DADDY": "Kid's word for father",
    "DAIRY": "Milk, cheese, and eggs' aisle",
    "DAISY": "Simple white-petaled flower",
    "DANDY": "Just fine",
    "DEALT": "Past tense of deal",
    "DEBUT": "First public appearance",
    "DECAY": "Tooth's slow enemy",
    "DECOR": "Room's style",
    "DEFER": "Put off until later",
    "DEITY": "God or goddess",
    "DELTA": "River's mouth shape",
    "DEMON": "Devilish creature",
    "DENSE": "Thick, or slow to catch on",
    "DEPOT": "Bus station",
    "DERBY": "Horse race, or a hat style",
    "DEVIL": "Horned troublemaker",
    "DIARY": "Locked personal journal",
    "DIGIT": "Finger, or a single number",
    "DINER": "Roadside diner's regular",
    "DINGY": "Grimy",
    "DISCO": "1970s dance floor's genre",
    "DITCH": "Roadside gutter, or to abandon",
    "DIVER": "Scuba explorer",
    "DODGE": "Sidestep",
    "DOGMA": "Rigid belief system",
    "DOING": "Currently at work on",
    "DONOR": "Blood drive's contributor",
    "DOUGH": "Bread's raw form, or slang for money",
    "DRAKE": "Male duck",
    "DRAPE": "Curtain",
    "DRAWL": "Slow Southern accent",
    "DREAD": "Deep worry",
    "DRIER": "More parched",
    "DRIFT": "Snow's windblown pile",
    "DRILL": "Dentist's tool, or a fire practice",
    "DROID": "Sci-fi robot, for short",
    "DROOP": "Wilt",
    "DROVE": "Past tense of drive",
    "DRUNK": "Had too much to drink",
    "DRYER": "Laundry's tumbling machine",
    "DUVET": "Fluffy bed cover",
    "DWELL": "Live, or linger on a thought",
    "EAGLE": "Bald bird on the dollar",
    "EASEL": "Painter's canvas stand",
    "EATEN": "Past participle of eat",
    "EBONY": "Deep black wood",
    "ELATE": "Fill with joy",
    "ELDER": "Older, wiser one",
    "ELECT": "Vote into office",
    "ELITE": "The very best",
    "EMAIL": "Inbox's contents",
    "EMBER": "Dying fire's glowing coal",
    "ENACT": "Pass into law",
    "ENDED": "Finished",
    "ENEMY": "Rival",
    "ENSUE": "Follow as a result",
    "EPOCH": "Historical age",
    "ERASE": "Wipe away with a rubber",
    "ERUPT": "Volcano's outburst",
    "ESSAY": "School's writing assignment",
    "ETHIC": "Moral principle",
    "EVOKE": "Bring to mind",
    "EXALT": "Praise highly",
    "EXCEL": "Do exceptionally well",
    "FABLE": "Aesop's short moral tale",
    "FACED": "Confronted",
    "FARCE": "Ridiculous, over-the-top comedy",
    "FATAL": "Deadly",
    "FAULT": "Tennis's service error",
    "FAVOR": "Ask a friend for one",
    "FEAST": "Thanksgiving spread",
    "FELON": "Convicted criminal",
    "FENCE": "Backyard's boundary",
    "FETCH": "Dog's favorite game",
    "FEVER": "Thermometer's warning sign",
    "FIBER": "Cereal box's nutrient",
    "FILLY": "Young female horse",
    "FILTH": "Grime",
    "FINCH": "Small backyard songbird",
    "FLAIR": "Stylish flourish",
    "FLAKE": "Snow's basic unit",
    "FLANK": "Steak cut, or a side approach",
    "FLARE": "Distress signal",
    "FLASH": "Camera's burst of light",
    "FLEET": "Ship squadron, or swift",
    "FLESH": "Skin and muscle",
    "FLICK": "Quick movie, informally",
    "FLING": "Toss, or a brief romance",
    "FLINT": "Fire-starting stone",
    "FLIRT": "Bat your eyelashes",
    "FLOAT": "Parade's decorated vehicle",
    "FLOCK": "Group of sheep",
    "FLUID": "Liquid",
    "FLUKE": "Lucky accident",
    "FLUNG": "Past tense of fling",
    "FLUTE": "High-pitched woodwind",
    "FOAMY": "Bubbly on top",
    "FOGGY": "Hard to see through",
    "FORAY": "Brief venture into something new",
    "FORGE": "Blacksmith's fiery workshop",
    "FORGO": "Do without",
    "FORTE": "Your strong suit",
    "FOYER": "House's entrance hall",
    "FRAIL": "Delicate",
    "FRANK": "Blunt and honest",
    "FRAUD": "Scam",
    "FREAK": "Go wild",
    "FRIED": "Cooked in hot oil",
    "FRISK": "Security pat-down",
    "FROND": "Fern's leaf",
    "FROTH": "Cappuccino's foam",
    "FROWN": "Upside-down smile",
    "FROZE": "Past tense of freeze",
    "FUDGE": "Rich chocolate square",
    "FUNGI": "Mushrooms, plural",
    "FUROR": "Public outcry",
    "FUSSY": "Hard to please",
    "FUZZY": "Not in sharp focus",
    "GABBY": "Chatty",
    "GAMER": "Console controller's owner",
    "GASSY": "Full of bubbles",
    "GAUGE": "Fuel tank's meter",
    "GAUZE": "Bandage's material",
    "GAWKY": "Awkwardly tall",
    "GEEKY": "Enthusiastically nerdy",
    "GENIE": "Lamp's wish granter",
    "GENRE": "Movie's category",
    "GIDDY": "Excitedly dizzy",
    "GLAND": "Body's hormone factory",
    "GLARE": "Sunlight's harsh reflection",
    "GLAZE": "Donut's shiny coating",
    "GLEAM": "Soft shine",
    "GLIDE": "Skate smoothly",
    "GLINT": "Quick flash of light",
    "GLOAT": "Rub it in",
    "GLOOM": "Dreary mood",
    "GLORY": "Triumphant fame",
    "GLOSS": "Lip balm's shine",
    "GLOVE": "Baseball's catching mitt",
    "GNOME": "Garden's little statue",
    "GOOEY": "Melted-cheese sticky",
    "GORGE": "Deep canyon, or to overeat",
    "GRACE": "Elegant poise",
    "GRAIN": "Wheat kernel",
    "GRAPE": "Wine's raw ingredient",
    "GRAPH": "Data's plotted line",
    "GRASP": "Firm hold, or understand",
    "GRATE": "Cheese's shredding tool",
    "GRAVE": "Tombstone's plot, or serious",
    "GRAVY": "Turkey dinner's topping",
    "GRAZE": "Cow's grassy grazing, or a scrape",
    "GREED": "Wanting more than your share",
    "GREET": "Say hello to",
    "GRIME": "Stubborn dirt",
    "GRIND": "Coffee bean's fate",
    "GRIPE": "Complain",
    "GROAN": "Dad joke's usual reaction",
    "GROOM": "Wedding's other star",
    "GROVE": "Small cluster of trees",
    "GROWL": "Angry dog's warning",
    "GRUFF": "Rough-mannered",
    "GRUMP": "Sourpuss",
    "GUILD": "Medieval trade association",
    "GUILT": "Conscience's nagging feeling",
    "GULLY": "Small ravine",
    "GUMBO": "Louisiana stew",
    "GUPPY": "Small aquarium fish",
    "GUSTO": "Enthusiastic energy",
    "GUTSY": "Bold",
    "HABIT": "Nail-biting, for one",
    "HANDY": "Good with tools",
    "HARDY": "Tough enough to survive",
    "HARPY": "Nagging shrew, in myth",
    "HASTY": "Rushed",
    "HATCH": "Egg's breaking-open moment",
    "HAUNT": "Ghost's favorite pastime",
    "HAVEN": "Safe refuge",
    "HAVOC": "Total chaos",
    "HAZEL": "Light brown eye color",
    "HEARD": "Past tense of hear",
    "HEDGE": "Trimmed shrub border",
    "HEFTY": "Heavy",
    "HINGE": "Door's swinging joint",
    "HIPPO": "River-dwelling heavyweight",
    "HITCH": "Small snag",
    "HOARD": "Squirrel's nut stockpile",
    "HOBBY": "Weekend pastime",
    "HOIST": "Lift up",
    "HOMER": "Baseball's over-the-fence hit",
    "HONOR": "Deep respect",
    "HORDE": "Large unruly crowd",
    "HOUND": "Hunting dog",
    "HOVER": "Drone's midair trick",
    "HUMID": "Sticky, weather-wise",
    "HUNCH": "Gut feeling",
    "HURRY": "Rush",
    "HUSKY": "Sled dog breed",
    "HUTCH": "Rabbit's cage",
    "HYENA": "Cackling scavenger",
    "HYPER": "Bouncing off the walls",
    "ICING": "Cake's sweet topping",
    "IDIOM": "Figure of speech",
    "IDIOT": "Fool",
    "IGLOO": "Ice block dwelling",
    "IMPLY": "Hint at without saying outright",
    "INEPT": "Clumsy at the task",
    "INFER": "Read between the lines",
    "INLET": "Small coastal bay",
    "IRATE": "Furious",
    "IRONY": "Saying one thing, meaning another",
    "IVORY": "Elephant tusk's material",
    "JELLY": "Toast's fruity spread",
    "JOKER": "Deck's wild card",
    "JOLLY": "Merry",
    "JUMBO": "Extra-large",
    "JUMPY": "On edge",
    "JUROR": "Courtroom's decision maker",
    "KARMA": "What goes around",
    "KAYAK": "Palindrome paddle boat",
    "KIOSK": "Mall's small stand",
    "KITTY": "Poker's pooled money, or a cat",
    "KNEEL": "Get down on one knee",
    "KNOWN": "Widely recognized",
    "KOALA": "Eucalyptus-munching marsupial",
    "LADLE": "Soup's serving spoon",
    "LAGER": "Light, crisp beer style",
    "LAPEL": "Suit jacket's flap",
    "LAPSE": "Brief slip",
    "LARVA": "Caterpillar's life stage",
    "LATCH": "Gate's simple lock",
    "LEAFY": "Full of greens",
    "LEAKY": "Not watertight",
    "LEASE": "Apartment's rental agreement",
    "LEDGE": "Cliff's narrow shelf",
    "LEECH": "Blood-sucking worm",
    "LEGAL": "Allowed by law",
    "LIKEN": "Compare to",
    "LINEN": "Crisp summer fabric",
    "LIVER": "Body's filtering organ",
    "LLAMA": "Andes pack animal",
    "LOBBY": "Hotel's entrance area",
    "LODGE": "Ski resort's main building",
    "LOFTY": "Grand in ambition",
    "LOTUS": "Sacred water flower",
    "LOUSY": "Terrible",
    "LUCKY": "Fortunate",
    "LUNAR": "Moon-related",
    "LYING": "Not telling the truth",
    "LYRIC": "Song's words",
    "MACRO": "Big-picture view",
    "MADAM": "Formal address for a woman",
    "MAKER": "Creator",
    "MAMBO": "Latin dance style",
    "MANGO": "Sweet tropical fruit",
    "MANIA": "Wild craze",
    "MANLY": "Macho",
    "MANOR": "Countryside estate",
    "MAPLE": "Syrup's tree",
    "MARCH": "Protest's forward walk",
    "MARRY": "Say I do",
    "MARSH": "Soggy wetland",
    "MATCH": "Tennis showdown, or a lit stick",
    "MAYBE": "Noncommittal answer",
    "MEDAL": "Olympic podium's reward",
    "MELON": "Cantaloupe, broadly",
    "MERCY": "Compassionate leniency",
    "MESSY": "In disarray",
    "METER": "Parking's coin slot",
    "METRO": "Subway system",
    "MINER": "Coal digger",
    "MINUS": "Subtraction's sign",
    "MISTY": "Hazy with fog",
    "MODEM": "Router's older cousin",
    "MOGUL": "Ski slope's bump, or a tycoon",
    "MOIST": "Slightly damp",
    "MOLAR": "Back tooth for grinding",
    "MOTEL": "Roadside overnight stop",
    "MOUND": "Pitcher's raised spot",
    "MUDDY": "Caked in mud",
    "MUMMY": "Ancient wrapped remains",
    "MURAL": "Wall-sized artwork",
    "MURKY": "Cloudy, hard to see through",
    "MUSTY": "Stale, damp smell",
    "NAIVE": "Overly trusting",
    "NASAL": "Nose-related, or stuffy-sounding",
    "NEEDY": "Overly dependent",
    "NEWLY": "Just recently",
    "NICHE": "Specialized market",
    "NIFTY": "Neat, clever",
    "NINJA": "Stealthy warrior",
    "NOMAD": "Wanderer with no fixed home",
    "NOOSE": "Rope's dangerous loop",
    "NOTCH": "Small carved groove",
    "NUDGE": "Gentle push",
    "NUTTY": "A little crazy, or full of nuts",
    "OASIS": "Desert's watering hole",
    "OCCUR": "Take place",
    "OLIVE": "Martini's garnish",
    "ONION": "Layered kitchen staple",
    "OPERA": "Sung stage drama",
    "ORBIT": "Planet's path around the sun",
    "ORGAN": "Church's big instrument",
    "OUNCE": "Sixteenth of a pound",
    "OUTDO": "Beat at their own game",
    "OWLET": "Baby owl",
    "OZONE": "Atmosphere's protective layer",
    "PADDY": "Rice field",
    "PAGAN": "Ancient nature worshipper",
    "PANIC": "Sudden alarm",
    "PANSY": "Cheerful garden flower",
    "PARKA": "Winter's insulated coat",
    "PASTE": "Glue stick's contents",
    "PATIO": "Backyard's paved hangout",
    "PATTY": "Burger's flat centerpiece",
    "PEACH": "Fuzzy summer fruit",
    "PEARL": "Oyster's prized gem",
    "PECAN": "Southern pie's nut",
    "PENNY": "One-cent coin",
    "PERCH": "Bird's resting spot",
    "PERKY": "Upbeat",
    "PESKY": "Annoying",
    "PETAL": "Flower's colorful part",
    "PIGGY": "Little pig",
    "PINCH": "Salt's small amount",
    "PINTO": "Speckled bean or pony",
    "PIPER": "Bagpipe player",
    "PIVOT": "Basketball's foot-planted turn",
    "PIXEL": "Screen's tiniest dot",
    "PIZZA": "Delivery box's contents",
    "PLAID": "Flannel's crisscross pattern",
    "PLANK": "Pirate's walk, or a core exercise",
    "PLAZA": "Town's open square",
    "PLEAT": "Skirt's folded crease",
    "PLUMB": "Perfectly vertical",
    "PLUME": "Feather, or a rising cloud",
    "PLUMP": "Nicely rounded",
    "PLUSH": "Stuffed animal's texture",
    "POACH": "Cook an egg gently in water",
    "POKER": "Card game with a bluff",
    "POLAR": "Arctic-related",
    "POLIO": "Disease Salk's vaccine beat",
    "POLKA": "Bouncy accordion dance",
    "POPPY": "Bright red field flower",
    "PORCH": "Front step's covered sitting area",
    "POSSE": "Sheriff's backup crew",
    "POUCH": "Kangaroo's built-in pocket",
    "PRANK": "April Fools' specialty",
    "PRAWN": "Big shrimp",
    "PREEN": "Bird's feather-fixing routine",
    "PRISM": "Rainbow-splitting glass",
    "PROBE": "Space mission's unmanned craft",
    "PRONE": "Lying face down, or likely to",
    "PROSE": "Ordinary writing, not verse",
    "PROVE": "Show it's true",
    "PROWL": "Cat's nighttime creep",
    "PRUNE": "Dried plum, or to trim",
    "PUDGY": "Chubby",
    "PUFFY": "Puffed up",
    "PULPY": "Full of orange juice's bits",
    "PUNCH": "Boxing's basic move",
    "PUPPY": "Baby dog",
    "PURSE": "Handbag",
    "QUACK": "Duck's sound, or a fake doctor",
    "QUAIL": "Small game bird",
    "QUAKE": "Earthquake, for short",
    "QUERY": "Database's search request",
    "QUEST": "Video game's mission",
    "QUILL": "Old-fashioned ink pen",
    "QUILT": "Patchwork blanket",
    "QUIRK": "Odd little habit",
    "QUOTE": "Speech's exact words, in marks",
    "RABID": "Foaming-at-the-mouth aggressive",
    "RADAR": "Palindrome that tracks planes",
    "RAINY": "Umbrella weather",
    "RALLY": "Comeback surge, or a protest gathering",
    "RANCH": "Cattle spread, or a salad dressing",
    "REFER": "Point someone elsewhere",
    "REIGN": "Monarch's time on the throne",
    "RELAY": "Track team's baton race",
    "RESIN": "Amber's raw sticky form",
    "RETRO": "Throwback style",
    "RHYME": "Poem's matching end sounds",
    "RIDGE": "Mountain's long crest",
    "RIFLE": "Long-barreled gun",
    "RIGID": "Stiff, unbending",
    "ROACH": "Kitchen's unwelcome bug",
    "ROAST": "Sunday dinner's centerpiece, or a friendly insult",
    "ROBIN": "Spring's red-breasted bird",
    "ROGUE": "Charming outlaw",
    "ROOMY": "Spacious",
    "ROOST": "Chicken's overnight perch",
    "ROTOR": "Helicopter's spinning blade",
    "ROUGE": "Cheek's blush color",
    "ROVER": "Mars mission's little robot car",
    "RULER": "Ruler of a nation, or a measuring stick",
    "RURAL": "Countryside, not city",
    "RUSTY": "Not practiced lately",
    "SADLY": "Unfortunately",
    "SALON": "Haircut's setting",
    "SALSA": "Chip's dip, or a dance style",
    "SALTY": "Seasoned with salt, or bitter about a loss",
    "SANDY": "Beach-colored",
    "SATIN": "Smooth, shiny fabric",
    "SAUNA": "Steamy relaxation room",
    "SAVOR": "Enjoy slowly",
    "SAVVY": "Street-smart",
    "SCALD": "Burn with hot liquid",
    "SCALP": "Head's skin under the hair",
    "SCAMP": "Mischievous kid",
    "SCANT": "Barely enough",
    "SCARF": "Winter neck wrap",
    "SCARY": "Fright-inducing",
    "SCENT": "Perfume's smell",
    "SCOLD": "Tell off",
    "SCONE": "Tea time's crumbly pastry",
    "SCOOP": "Ice cream server's tool",
    "SCOOT": "Move over a little",
    "SCOUT": "Merit badge's earner",
    "SCRAP": "Leftover bit, or a small fight",
    "SCREW": "Bolt's twisted cousin",
    "SCRUB": "Clean vigorously",
    "SCUBA": "Underwater breathing gear",
    "SEIZE": "Grab suddenly",
    "SETUP": "How the pieces are arranged",
    "SEWER": "Underground drainage pipe",
    "SHACK": "Small, rough cabin",
    "SHADY": "Suspicious",
    "SHAFT": "Elevator's vertical passage",
    "SHAKY": "Trembling",
    "SHALE": "Layered sedimentary rock",
    "SHAME": "Deep embarrassment",
    "SHARD": "Broken glass fragment",
    "SHARK": "Fin above the water",
    "SHAWL": "Grandmother's shoulder wrap",
    "SHEAR": "Clip a sheep's wool",
    "SHEER": "Completely, or see-through",
    "SHINY": "Reflecting light",
    "SHONE": "Past tense of shine",
    "SHORE": "Beach's edge",
    "SHOVE": "Rough push",
    "SHREW": "Small, sharp-tongued mammal",
    "SHRUB": "Bush",
    "SHRUG": "Noncommittal shoulder move",
    "SIEGE": "Castle's long standoff",
    "SINGE": "Slightly burn",
    "SIREN": "Fire truck's wail",
    "SIXTY": "Minutes in an hour",
    "SKATE": "Ice rink's footwear",
    "SKIER": "Slope's descender",
    "SKIMP": "Cut corners on",
    "SKIRT": "Below-the-waist garment",
    "SKULL": "Head's bony frame",
    "SKUNK": "Backyard's smelly visitor",
    "SLACK": "Rope's loose part",
    "SLANG": "Casual street talk",
    "SLASH": "Diagonal punctuation mark",
    "SLATE": "Chalkboard's material, or a clean start",
    "SLEEK": "Smooth and stylish",
    "SLEET": "Icy rain mix",
    "SLICK": "Slippery, or smooth-talking",
    "SLIME": "Kid's stretchy toy goo",
    "SLIMY": "Gross and wet",
    "SLING": "Broken arm's support",
    "SLOPE": "Ski hill's incline",
    "SLOTH": "Slow-moving rainforest mammal",
    "SLUMP": "Batting cold streak",
    "SLURP": "Loud noodle-eating sound",
    "SMACK": "Sharp slap",
    "SMASH": "Hit hard",
    "SMOCK": "Painter's protective coat",
    "SMOKY": "Tasting of the campfire",
    "SNACK": "Between-meal bite",
    "SNAIL": "Garden's slow shelled traveler",
    "SNARE": "Trap, or a drum type",
    "SNARL": "Tangled mess, or an angry growl",
    "SNEAK": "Move quietly",
    "SNEER": "Contemptuous smirk",
    "SNIFF": "Take a small smell",
    "SNIPE": "Take a cheap shot at",
    "SNORE": "Sleeping's noisy sound",
    "SNORT": "Pig's sound, or a burst of laughter",
    "SNOUT": "Pig's nose",
    "SOAPY": "Full of suds",
    "SOBER": "Not intoxicated",
    "SOGGY": "Waterlogged",
    "SOLAR": "Sun-powered",
    "SONIC": "Sound-related, or a hedgehog's name",
    "SOOTY": "Covered in chimney ash",
    "SPADE": "Card suit, or a digging tool",
    "SPARK": "Campfire's first flicker",
    "SPASM": "Sudden muscle jerk",
    "SPAWN": "Fish eggs, or to create",
    "SPEAR": "Ancient hunting weapon",
    "SPICY": "Hot on the tongue",
    "SPIED": "Caught sight of secretly",
    "SPIKE": "Volleyball's power hit",
    "SPILL": "Coffee cup's accident",
    "SPINE": "Book's bound edge, or your backbone",
    "SPINY": "Covered in prickles",
    "SPOIL": "Turn rotten, or ruin the ending",
    "SPOKE": "Past tense of speak",
    "SPOOF": "Comedy's parody",
    "SPOOK": "Give a scare",
    "SPOOL": "Thread's wound-up holder",
    "SPOON": "Cereal's utensil",
    "SPORE": "Mushroom's tiny reproductive cell",
    "SPREE": "Shopping binge",
    "SPRIG": "Small herb branch",
    "SPUNK": "Feisty energy",
    "SQUAD": "Team, informally",
    "SQUAT": "Gym's leg exercise",
    "SQUID": "Ten-armed sea creature",
    "STAIN": "Carpet's spilled-wine mark",
    "STAKE": "Tent's ground anchor",
    "STALE": "No longer fresh",
    "STALK": "Corn's tall stem",
    "STALL": "Delay, or a horse's pen",
    "STASH": "Hidden supply",
    "STEAM": "Kettle's hot vapor",
    "STEED": "Knight's horse",
    "STEEP": "Sharp incline, or pricey",
    "STEER": "Guide the wheel",
    "STERN": "Ship's back, or strict",
    "STINK": "Bad smell",
    "STINT": "Short period of work",
    "STOIC": "Emotionally unshaken",
    "STOKE": "Fire up the enthusiasm",
    "STOLE": "Past tense of steal",
    "STOMP": "Heavy-footed step",
    "STOOD": "Past tense of stand",
    "STOOL": "Backless seat",
    "STOOP": "Bend down, or a front step",
    "STORK": "Baby-delivering bird of legend",
    "STOUT": "Sturdy, or a dark beer",
    "STRAY": "Wandering cat with no home",
    "STRIP": "Comic's row of panels",
    "STRUT": "Confident walk",
    "STUCK": "Not able to move",
    "STUMP": "Tree's leftover base",
    "STUNT": "Movie's dangerous scene",
    "SUEDE": "Soft napped leather",
    "SUITE": "Hotel's roomy upgrade",
    "SULKY": "Pouting",
    "SUNNY": "Bright and cheerful",
    "SURGE": "Sudden rush",
    "SUSHI": "Raw fish and rice",
    "SWAMP": "Murky wetland",
    "SWARM": "Bees' buzzing group",
    "SWEEP": "Broom's job",
    "SWELL": "Grow larger, or a big wave",
    "SWEPT": "Past tense of sweep",
    "SWINE": "Pig, formally",
    "SWIRL": "Soft-serve's twisty shape",
    "SWISH": "Basketball's perfect no-rim shot",
    "SWOON": "Faint from excitement",
    "SWORD": "Knight's blade",
    "SWORE": "Past tense of swear",
    "SWUNG": "Past tense of swing",
    "SYRUP": "Pancake's sticky topping",
    "TABBY": "Striped house cat",
    "TACKY": "In poor taste",
    "TAFFY": "Chewy boardwalk candy",
    "TANGO": "It takes two",
    "TANGY": "Zesty on the tongue",
    "TAROT": "Fortune teller's cards",
    "TEASE": "Playfully mock",
    "TEETH": "Smile's contents",
    "TEMPO": "Song's speed",
    "TENOR": "High male singing voice",
    "TENSE": "On edge",
    "TENTH": "After ninth",
    "TEPID": "Lukewarm",
    "TERSE": "Curt, few words",
    "THEFT": "Robbery",
    "THEME": "Party's dress-up idea",
    "THIEF": "Robber",
    "THIGH": "Above the knee",
    "THORN": "Rose's prickly defense",
    "THROB": "Headache's pulsing pain",
    "THUMP": "Heavy footstep sound",
    "THYME": "Fragrant kitchen herb",
    "TIARA": "Pageant winner's crown",
    "TIMID": "Shy",
    "TIMER": "Kitchen's countdown clock",
    "TINGE": "Faint trace of color",
    "TIPSY": "A little drunk",
    "TITAN": "Giant of industry",
    "TOAST": "Breakfast's crisped bread",
    "TOKEN": "Arcade's coin substitute",
    "TONIC": "Gin's fizzy mixer",
    "TOPAZ": "Yellow birthstone",
    "TORCH": "Olympic runner's flame",
    "TORSO": "Body without the limbs",
    "TOXIC": "Poisonous",
    "TRACE": "Faint hint of",
    "TRACT": "Stretch of land",
    "TRAIT": "Inherited feature",
    "TRAMP": "Wanderer, or a heavy footstep",
    "TRASH": "Curbside bin's contents",
    "TRIBE": "Close-knit group",
    "TRIED": "Attempted",
    "TROOP": "Scout group",
    "TRUCE": "Ceasefire",
    "TRUNK": "Elephant's nose, or a car's back storage",
    "TULIP": "Dutch spring flower",
    "TUMMY": "Kid's word for stomach",
    "TUNIC": "Loose-fitting top",
    "TURBO": "Engine's speed boost",
    "TUTOR": "After-school helper",
    "TWEAK": "Small adjustment",
    "TWEED": "Rustic wool fabric",
    "TWIRL": "Spin around",
    "TWIST": "Plot's surprise turn",
    "TWEET": "Bird's chirp, or a short online post",
    "TYPED": "Entered on a keyboard",
    "ULTRA": "Extremely",
    "UNDID": "Reversed",
    "UNDUE": "Excessive",
    "UNIFY": "Bring together",
    "UNITE": "Join forces",
    "UPSET": "Sports' surprise defeat",
    "URGED": "Strongly encouraged",
    "USAGE": "How something is used",
    "UTTER": "Say out loud, or complete",
    "VAPOR": "Steam's form",
    "VAULT": "Bank's secure room",
    "VENOM": "Snake's bite payload",
    "VENUE": "Concert's location",
    "VERSE": "Poem's stanza",
    "VIGOR": "Energetic strength",
    "VILLA": "Countryside vacation house",
    "VINYL": "Old-school record format",
    "VIOLA": "Violin's bigger cousin",
    "VIRUS": "Computer's malware, or a cold's cause",
    "VISOR": "Cap's brim, or a helmet's shield",
    "VITAL": "Absolutely essential",
    "VIVID": "Bright and clear",
    "VOCAL": "Outspoken, or singing-related",
    "VODKA": "Clear Russian spirit",
    "VOGUE": "Current fashion trend",
    "VOWEL": "A, E, I, O, or U",
    "WAFER": "Thin crisp cookie",
    "WAGON": "Little red kid-puller",
    "WAIST": "Belt's resting place",
    "WALTZ": "Three-beat ballroom dance",
    "WEARY": "Worn out",
    "WEAVE": "Loom's over-under motion",
    "WEDGE": "Golf club, or a doorstop shape",
    "WEIRD": "Odd",
    "WHALE": "Ocean's biggest mammal",
    "WHARF": "Dock for loading ships",
    "WHINE": "Kid's whiny complaint",
    "WHIRL": "Spin fast",
    "WHISK": "Egg-beating kitchen tool",
    "WIDOW": "A late husband's spouse",
    "WIDTH": "How wide something is",
    "WITCH": "Broomstick rider",
    "WOMAN": "Adult female",
    "WOVEN": "Interlaced, like a basket",
    "WRATH": "Fierce anger",
    "WRECK": "Totaled car",
    "WRONG": "Incorrect",
    "YACHT": "Billionaire's boat",
    "YEAST": "Bread's rising agent",
    "YIELD": "Traffic sign's caution",
    "ZEBRA": "Striped African grazer",
})


def build_clues_and_words():
    clues = {}
    curated_by_len = {3: [], 4: [], 5: []}
    for length, table in ((3, WORDS_3), (4, WORDS_4), (5, WORDS_5)):
        for word, clue in table.items():
            if len(word) != length or not word.isalpha() or word != word.upper():
                print(f"warning: dropping malformed entry {word!r}", file=sys.stderr)
                continue
            clues[word] = clue
            curated_by_len[length].append(word)
    return clues, curated_by_len


CLUES, CURATED_BY_LEN = build_clues_and_words()
CURATED_SET = set(CLUES.keys())


# The generator fills ONLY from the curated, hand-clued word set above.
# An earlier version fell back to the full shared wordlist.txt (ENABLE) for
# slots the curated list couldn't satisfy; a discovery run of that fallback
# surfaced a slur among the candidates. ENABLE is a Scrabble word list, not a
# vetted "fine to show a stranger on a puzzle page" list, and there is no
# cheap way to filter it down to that bar. So there is no fallback: every
# answer that can ever appear comes from CLUES, which this file's author
# wrote and can vouch for. See enumerate_solutions and main for how the bank
# is built and validated from this vocabulary alone.
FALLBACK_BY_LEN = {3: [], 4: [], 5: []}
WORDS_BY_LEN = {length: CURATED_BY_LEN[length] for length in (3, 4, 5)}


def build_position_index():
    """index[length][position][letter] -> tuple of candidate words.

    Lets domain filtering intersect index sets instead of rescanning every
    word in the pool at every backtracking node.
    """
    index = {}
    for length, words in WORDS_BY_LEN.items():
        by_pos = [{} for _ in range(length)]
        for w in words:
            for pos, ch in enumerate(w):
                by_pos[pos].setdefault(ch, []).append(w)
        index[length] = [{ch: frozenset(ws) for ch, ws in pos_map.items()} for pos_map in by_pos]
    return index


POSITION_INDEX = build_position_index()

# ---------------------------------------------------------------------------
# Grid templates (see module docstring for the proof these are the only
# symmetric block placements that keep every entry length >= 3).
# ---------------------------------------------------------------------------

CORNERS = {"tl": (0, 0), "tr": (0, 4), "bl": (4, 0), "br": (4, 4)}
TEMPLATES = {
    0: [frozenset()],
    2: [frozenset({CORNERS["tl"], CORNERS["br"]}), frozenset({CORNERS["tr"], CORNERS["bl"]})],
    4: [frozenset(CORNERS.values())],
}


def segments_ok(is_block, length, index_range, cell_at):
    """A row or column is valid if every maximal open run is length 0 or >= 3."""
    run = 0
    for i in index_range:
        if is_block(*cell_at(i)):
            if 0 < run < 3:
                return False
            run = 0
        else:
            run += 1
    return not (0 < run < 3)


def validate_template(blocks):
    is_block = lambda r, c: (r, c) in blocks
    for r in range(SIZE):
        if not segments_ok(is_block, SIZE, range(SIZE), lambda c, r=r: (r, c)):
            return False
    for c in range(SIZE):
        if not segments_ok(is_block, SIZE, range(SIZE), lambda r, c=c: (r, c)):
            return False
    return True


for _count, _variants in TEMPLATES.items():
    for _blocks in _variants:
        assert validate_template(_blocks), f"template with {_count} blocks failed validation"


def compute_slots(blocks):
    """Mirrors games/minigrid/core.js parsePuzzle: same numbering algorithm."""
    is_block = lambda r, c: (r, c) in blocks
    slots = []

    for r in range(SIZE):
        c = 0
        while c < SIZE:
            if is_block(r, c):
                c += 1
                continue
            start = c
            while c < SIZE and not is_block(r, c):
                c += 1
            length = c - start
            if length >= 3:
                cells = [(r, cc) for cc in range(start, c)]
                slots.append({"dir": "across", "row": r, "col": start, "length": length, "cells": cells})

    for c in range(SIZE):
        r = 0
        while r < SIZE:
            if is_block(r, c):
                r += 1
                continue
            start = r
            while r < SIZE and not is_block(r, c):
                r += 1
            length = r - start
            if length >= 3:
                cells = [(rr, c) for rr in range(start, r)]
                slots.append({"dir": "down", "row": start, "col": c, "length": length, "cells": cells})

    starts = {(s["row"], s["col"]) for s in slots}
    numbering = {}
    n = 0
    for r in range(SIZE):
        for c in range(SIZE):
            if is_block(r, c):
                continue
            if (r, c) in starts:
                n += 1
                numbering[(r, c)] = n
    for s in slots:
        s["number"] = numbering[(s["row"], s["col"])]
    return slots


def enumerate_solutions(slots, rng, cap=2000, node_budget=2_000_000, time_budget=40.0):
    """Depth-first search that keeps going past the first solution, collecting
    every complete filling it finds (up to cap) in one shared search tree.

    A restart-based solver (try random word order, give up after a node/time
    budget, shuffle, try again) turned out to be a poor fit here: with 6
    mutually-crossing 5-letter slots, valid fillings are a small, oddly
    shaped island in the search space, so *independent* random restarts keep
    re-finding the same easy handful and burning their whole budget on the
    rest. A single DFS that doesn't stop at the first answer explores that
    same island exhaustively and finds every solution in it far faster than
    restarting ever could -- see the module's build history for the numbers
    (hundreds of complete fillings in single-digit seconds).
    """
    n = len(slots)
    assignment = {}
    grid = {}
    used_words = set()
    found = []
    nodes = 0
    deadline = time.monotonic() + time_budget

    order = {}
    for i, s in enumerate(slots):
        pool = list(CURATED_BY_LEN[s["length"]])
        rng.shuffle(pool)
        order[i] = pool
    rank = {i: {w: k for k, w in enumerate(pool)} for i, pool in order.items()}

    def domain(i):
        s = slots[i]
        idx = POSITION_INDEX[s["length"]]
        candidates = None
        for local_pos, (r, c) in enumerate(s["cells"]):
            letter = grid.get((r, c))
            if letter is None:
                continue
            bucket = idx[local_pos].get(letter)
            if not bucket:
                return []
            candidates = bucket if candidates is None else (candidates & bucket)
            if not candidates:
                return []
        candidates = list(candidates) if candidates is not None else list(WORDS_BY_LEN[s["length"]])
        # No answer word may appear twice in one puzzle (once across, once
        # down): it would hand a player half of one clue for free.
        candidates = [w for w in candidates if w not in used_words]
        candidates.sort(key=lambda w: rank[i][w])
        return candidates

    def dfs():
        nonlocal nodes
        if len(found) >= cap or nodes > node_budget or time.monotonic() > deadline:
            return
        nodes += 1
        if len(assignment) == n:
            found.append(dict(assignment))
            return
        best_i, best_dom = None, None
        for i in range(n):
            if i in assignment:
                continue
            d = domain(i)
            if best_dom is None or len(d) < len(best_dom):
                best_i, best_dom = i, d
            if not d:
                return
        for w in best_dom:
            placed = []
            conflict = False
            for (r, c), ch in zip(slots[best_i]["cells"], w):
                if (r, c) in grid:
                    if grid[(r, c)] != ch:
                        conflict = True
                        break
                else:
                    grid[(r, c)] = ch
                    placed.append((r, c))
            if conflict:
                for p in placed:
                    del grid[p]
                continue
            assignment[best_i] = w
            used_words.add(w)
            dfs()
            del assignment[best_i]
            used_words.discard(w)
            for p in placed:
                del grid[p]
            if len(found) >= cap or time.monotonic() > deadline:
                return

    dfs()
    return found


def assignment_to_puzzle(blocks, slots, assignment):
    grid_rows = []
    for r in range(SIZE):
        row = []
        for c in range(SIZE):
            if (r, c) in blocks:
                row.append("#")
            else:
                slot_i = next(i for i, s in enumerate(slots) if (r, c) in s["cells"])
                word = assignment[slot_i]
                local = next(k for k, cell in enumerate(slots[slot_i]["cells"]) if cell == (r, c))
                row.append(word[local])
        grid_rows.append("".join(row))

    clues = {"across": {}, "down": {}}
    for i, s in enumerate(slots):
        clues[s["dir"]][str(s["number"])] = CLUES[assignment[i]]
    return {"grid": grid_rows, "clues": clues}


def transpose_puzzle(puzzle):
    """Swaps rows/columns. Every one of this game's block templates is
    symmetric under transpose (see the module docstring), and swapping
    letters at (r, c) with (c, r) turns each across entry into a down entry
    reading the exact same letters in the exact same order, and vice versa.
    So this always yields a second fully valid, distinct puzzle for free
    from the same solved grid, at no extra search cost.
    """
    grid = puzzle["grid"]
    t_grid = ["".join(grid[c][r] for c in range(SIZE)) for r in range(SIZE)]
    blocks = {(r, c) for r in range(SIZE) for c in range(SIZE) if t_grid[r][c] == "#"}
    slots = compute_slots(blocks)
    clues = {"across": {}, "down": {}}
    for s in slots:
        word = "".join(t_grid[r][c] for r, c in s["cells"])
        clues[s["dir"]][str(s["number"])] = CLUES[word]
    return {"grid": t_grid, "clues": clues}


def load_wordlist():
    words = set()
    with WORDLIST_PATH.open(encoding="utf-8") as f:
        for line in f:
            w = line.strip()
            if w:
                words.add(w.lower())
    return words


def validate_bank(puzzles, dictionary):
    assert len(puzzles) > 0, "bank is empty"
    seen = set()
    for i, p in enumerate(puzzles):
        grid = p["grid"]
        assert len(grid) == SIZE, f"puzzle {i}: grid must have {SIZE} rows"
        for row in grid:
            assert len(row) == SIZE, f"puzzle {i}: row length must be {SIZE}"
            for ch in row:
                assert ch == "#" or ("A" <= ch <= "Z"), f"puzzle {i}: bad char {ch!r}"

        sig = tuple(grid)
        assert sig not in seen, f"puzzle {i}: duplicate grid"
        seen.add(sig)

        blocks = {(r, c) for r in range(SIZE) for c in range(SIZE) if grid[r][c] == "#"}
        assert any(blocks == v for variants in TEMPLATES.values() for v in variants), (
            f"puzzle {i}: block pattern is not one of the proven-valid templates"
        )

        slots = compute_slots(blocks)
        by_dir = {"across": {}, "down": {}}
        for s in slots:
            assert s["length"] in (3, 4, 5), f"puzzle {i}: entry length {s['length']} out of range"
            word = "".join(grid[r][c] for r, c in s["cells"])
            assert word.lower() in dictionary, f"puzzle {i}: {word} is not in the shared wordlist"
            by_dir[s["dir"]][str(s["number"])] = word

        for direction in ("across", "down"):
            got_numbers = set(p["clues"][direction].keys())
            expect_numbers = set(by_dir[direction].keys())
            assert got_numbers == expect_numbers, (
                f"puzzle {i}: {direction} clue numbers {got_numbers} do not match grid slots {expect_numbers}"
            )
            for num, clue_text in p["clues"][direction].items():
                word = by_dir[direction][num]
                assert clue_text == CLUES[word], f"puzzle {i}: clue for {word} does not match the curated text"
                assert clue_text.strip() == clue_text and clue_text, f"puzzle {i}: clue for {word} is malformed"
                for bad in ("\u2014", "\u2013", "\u2026"):
                    assert bad not in clue_text, f"puzzle {i}: clue for {word} has a forbidden character"


def main():
    parser = argparse.ArgumentParser(description="Generate the Minigrid puzzle bank.")
    parser.add_argument("--seed", type=int, default=20260810)
    parser.add_argument("--count", type=int, default=90)
    parser.add_argument("--out", type=Path, default=OUT_PATH)
    parser.add_argument(
        "--cap-per-template",
        type=int,
        default=800,
        help="max complete fillings to collect per block template before moving on",
    )
    args = parser.parse_args()

    rng = random.Random(args.seed)
    dictionary = load_wordlist()

    t0 = time.monotonic()
    # Search the 4-corner template first: it's the least dense (four
    # length-3 entries instead of length-5), so it has by far the largest
    # solution space for a given curated word count. See enumerate_solutions.
    all_variants = [
        (count, blocks) for count in (4, 2, 0) for blocks in TEMPLATES[count]
    ]
    puzzles = []
    seen_grids = set()
    template_uses = {}

    for count, blocks in all_variants:
        slots = compute_slots(blocks)
        solutions = enumerate_solutions(slots, rng, cap=args.cap_per_template)
        rng.shuffle(solutions)
        for assignment in solutions:
            base = assignment_to_puzzle(blocks, slots, assignment)
            for candidate in (base, transpose_puzzle(base)):
                sig = tuple(candidate["grid"])
                if sig in seen_grids:
                    continue
                seen_grids.add(sig)
                puzzles.append(candidate)
                template_uses[count] = template_uses.get(count, 0) + 1
        print(
            f"template blocks={count}: {len(solutions)} fillings found "
            f"({time.monotonic() - t0:.1f}s elapsed)"
        )
        if len(puzzles) >= args.count * 2:
            break  # plenty of headroom; no need to search the remaining templates

    rng.shuffle(puzzles)
    puzzles = puzzles[: args.count]

    validate_bank(puzzles, dictionary)
    print(f"generated {len(puzzles)} puzzles in {time.monotonic() - t0:.1f}s")

    OUT = args.out
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as f:
        json.dump({"puzzles": puzzles}, f, indent=2, ensure_ascii=True)
        f.write("\n")

    print(f"wrote {len(puzzles)} puzzles to {OUT}")
    print(f"template block-count usage: {template_uses}")
    if len(puzzles) < args.count:
        print(f"warning: requested {args.count} but only produced {len(puzzles)}", file=sys.stderr)


if __name__ == "__main__":
    main()
